
import { ServiceCategory, Language, TranslationSet, Professional } from './types';
import { Wrench, PlugZap, PaintRoller, Droplets, Hammer, Sofa } from './components/icons';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'ar', name: 'العربية' },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    icon: Droplets,
    name: {
      en: 'Plumbing',
      fr: 'Plomberie',
      ar: 'السباكة',
    },
  },
  {
    id: 'electrical',
    icon: PlugZap,
    name: {
      en: 'Electrical',
      fr: 'Électricité',
      ar: 'الكهرباء',
    },
  },
  {
    id: 'painting',
    icon: PaintRoller,
    name: {
      en: 'Painting',
      fr: 'Peinture',
      ar: 'الدهان',
    },
  },
  {
    id: 'carpentry',
    icon: Hammer,
    name: {
      en: 'Carpentry',
      fr: 'Menuiserie',
      ar: 'النجارة',
    },
  },
   {
    id: 'general_repair',
    icon: Wrench,
    name: {
      en: 'General Repair',
      fr: 'Réparation Générale',
      ar: 'إصلاحات عامة',
    },
  },
  {
    id: 'assembly',
    icon: Sofa,
    name: {
      en: 'Furniture Assembly',
      fr: 'Montage de Meubles',
      ar: 'تركيب الأثاث',
    },
  },
];

const professionalsData: Professional[] = [
  // Casablanca Plumbers
  { id: 1, name: 'ELWARDI Hassan', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Avenue Bordeaux', rating: 4.8, phone: '06 53 69 87 70', lat: 33.5854, lng: -7.6366 },
  { id: 2, name: 'EDDAIF Abdelmajid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.9, phone: '06 68 17 27 07', lat: 33.5862, lng: -7.5912 },
  { id: 3, name: 'FADLI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 42 75 38 93', lat: 33.528, lng: -7.6186 },
  { id: 4, name: 'KOKAJI Simohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.6, phone: '06 65 83 19 61', lat: 33.595, lng: -7.6338 },
  { id: 5, name: 'ELGARMA Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 75 47 64 51', lat: 33.5651, lng: -7.6309 },
  { id: 6, name: 'MOURAD Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.7, phone: '06 14 63 87 87', lat: 33.5831, lng: -7.5682 },
  { id: 7, name: 'AMROUG Hamid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '06 10 88 35 16', lat: 33.618, lng: -7.551 },
  { id: 8, name: 'ARGAZ Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Sebaa', rating: 4.8, phone: '06 00 57 29 47', lat: 33.5947, lng: -7.5619 },
  { id: 9, name: 'RAOUF Hicham', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.6, phone: '06 62 16 68 34', lat: 33.5943, lng: -7.5578 },
  { id: 10, name: 'ENNAKRI Abdelhadi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.7, phone: '06 15 74 15 33', lat: 33.578, lng: -7.5401 },
  { id: 11, name: 'BEL KHADRASSI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '06 67 26 85 15', lat: 33.565, lng: -7.5913 },
  { id: 12, name: 'BEN ARBIA Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '06 66 30 30 44', lat: 33.5283, lng: -7.6183 },
  { id: 13, name: 'AL MISRA Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Moumen', rating: 4.8, phone: '06 71 46 18 99', lat: 33.606, lng: -7.6187 },
  { id: 14, name: 'SENHAJI Abdennabi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Harrouda', rating: 4.7, phone: '06 62 01 74 59', lat: 33.5746, lng: -7.5856 },
  { id: 15, name: 'AIT BRAHIM Mohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 41 71 56 82', lat: 33.5655, lng: -7.5943 },
  { id: 16, name: 'ENNAINI Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.6, phone: '06 38 11 65 78', lat: 33.591, lng: -7.604 },
  { id: 17, name: 'ELASSOULI Houcine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.8, phone: '06 61 85 20 20', lat: 33.5768, lng: -7.6256 },
  { id: 18, name: 'KECHAF Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.5, phone: '06 63 59 06 10', lat: 33.5606, lng: -7.6072 },
  { id: 19, name: 'ERAYHANI Khalid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 64 74 33 46', lat: 33.582, lng: -7.6369 },
  { id: 20, name: 'AHBARI Mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.9, phone: '06 60 95 89 83', lat: 33.5638, lng: -7.5501 },
  { id: 21, name: 'EL OUAFI Yassine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.6, phone: '06 71 13 56 07', lat: 33.5752, lng: -7.636 },
  { id: 22, name: 'ALAMI Karim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.8, phone: '06 69 87 45 21', lat: 33.606, lng: -7.6201 },
  { id: 23, name: 'abdessamad biad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '0614149221', lat: 33.5414, lng: -7.5852 },
  { id: 24, name: 'HADDAD Ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '3, rue Ibrahim Hafid -ex Chateaubriand, Q. Gauthier - 20060', rating: 4.7, phone: '0522664088', lat: 33.598, lng: -7.5492 },
  { id: 25, name: 'nachit ayoub', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'derb el wydad blok 511 n 748 hay hassani', rating: 4.9, phone: '0630113133', lat: 33.5358, lng: -7.5755 },
  { id: 26, name: 'Selmouni Brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Maarif', rating: 4.6, phone: '0670398387', lat: 33.6191, lng: -7.5794 },
  { id: 27, name: 'El Fissaoui Youness', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '61 rue 1 khalil 2 la villette', rating: 4.8, phone: '0678636249', lat: 33.5678, lng: -7.6267 },
  { id: 28, name: 'SOKTRA', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '9, Bd Abdelmoumen', rating: 4.5, phone: '0655904767', lat: 33.5467, lng: -7.5663 },
  { id: 29, name: 'Youness Boujmad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Hay almasjid rue28 n 9 casa', rating: 4.7, phone: '0662713781', lat: 33.5937, lng: -7.6218 },
  { id: 30, name: 'mabsout abdelfattaj', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Rue 12 imm 6 n 12 residence khaled sekelia hay hassani', rating: 4.9, phone: '0679648647', lat: 33.5979, lng: -7.5422 },
  { id: 31, name: 'maddah mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'anassi al bernossi', rating: 4.6, phone: '0699901535', lat: 33.565, lng: -7.6166 },
  { id: 32, name: 'Aitbelahsen ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'bloc saada 301 bd grande ceinture N 367', rating: 4.8, phone: '0660565036', lat: 33.6171, lng: -7.6322 },
  { id: 33, name: 'ibra brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '0665426598', lat: 33.6186, lng: -7.6164 },
  
  // Rabat Plumbers
  { id: 34, name: 'ENNASRAOUI Jamal', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.7, phone: '06 41 14 66 24', lat: 34.0256, lng: -6.8123 },
  { id: 35, name: 'SMOUNI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 65 23 40 13/06 66 11 42 64', lat: 34.0416, lng: -6.8299 },
  { id: 36, name: 'SOUHADI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.6, phone: '06 22 68 47 03/06 77 92 19 67', lat: 34.0041, lng: -6.8839 },
  { id: 37, name: 'BENDADNI Bendadani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.5, phone: '05 37 69 91 93', lat: 34.0621, lng: -6.8378 },
  { id: 38, name: 'MBOUKI Omar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.9, phone: '06 73 30 49 49', lat: 34.0689, lng: -6.8208 },
  { id: 39, name: 'AADIM Youssef', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 74 37 23 73', lat: 33.971, lng: -6.882 },
  { id: 40, name: 'BOU INAN Abdelghani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Yacoub Al Mansour', rating: 4.8, phone: '06 65 06 66 18 / 06 35 46 39 75', lat: 34.0536, lng: -6.839 },
  { id: 41, name: 'AL MOHANDISS Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.6, phone: '06 70 94 05 83', lat: 34.0436, lng: -6.8211 },
  { id: 42, name: 'EL AMRANI Karim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 68 62 71 73', lat: 33.9928, lng: -6.843 },
  { id: 43, name: 'BEROUMI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.5, phone: '06 22 62 03 58', lat: 34.0534, lng: -6.8041 },
  { id: 44, name: 'KERROUMI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.7, phone: '06 66 08 12 52 / 06 6 1 32 10 42', lat: 34.0135, lng: -6.8872 },
  { id: 45, name: 'EL KALEM Ahmed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.8, phone: '06 63 03 80 73', lat: 34.016, lng: -6.8413 },
  { id: 46, name: 'DRISSAT Elarbi', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.6, phone: '06 68 01 22 03', lat: 34.048, lng: -6.8396 },
  { id: 47, name: 'ERRAZITMI Abdelkabir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 78 34 79 62', lat: 34.062, lng: -6.8406 },
  { id: 48, name: 'EL MAJDOULI Chankaoui', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'L\'Ocean', rating: 4.5, phone: '06 69 03 11 83', lat: 34.0175, lng: -6.831 },
  { id: 49, name: 'MOUNDA Lehcen', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 66 32 53 06', lat: 33.9749, lng: -6.8583 },
  { id: 50, name: 'EL OUAZZANI Abdessamad', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 66 84 41 48', lat: 34.0692, lng: -6.8447 },
  { id: 51, name: 'ERRAMADI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.6, phone: '06 66 01 07 46', lat: 33.9926, lng: -6.8797 },
  { id: 52, name: 'EL ALAOUI Hassan', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 63 88 81 20', lat: 34.0354, lng: -6.8778 },
  { id: 53, name: 'Ahmed Manar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '12 rue de hay riad', rating: 4.5, phone: '06636598541', lat: 34.0123, lng: -6.8837 },
  { id: 54, name: 'hicham chakir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'agdal', rating: 4.7, phone: '0630892791', lat: 34.0189, lng: -6.8436 },
  { id: 55, name: 'samlali youness', serviceId: 'plumbing', serviceCities: ['Rabat', 'Témara'], address: 'masira 1 n 33', rating: 4.8, phone: '0617546262', lat: 33.9754, lng: -6.8741 },
  { id: 56, name: 'Naji Hicham', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N° 470 CYM', rating: 4.6, phone: '0623503918', lat: 33.9877, lng: -6.875 },
  { id: 57, name: 'abdelmotalib ahdaf', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'AV HASSAN II N°24, Cité Almanar DIOUR JAMAA', rating: 4.9, phone: '06 23 47 77 12', lat: 33.9711, lng: -6.8458 },
  { id: 58, name: 'Boucetta Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N 1343 hay el manzah cym', rating: 4.7, phone: '0661735121', lat: 34.0205, lng: -6.8863 },

  // Salé Plumbers
  { id: 59, name: 'EL GOUILI Lahcen', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 03 66 91', lat: 34.0326, lng: -6.8623 },
  { id: 60, name: 'IBRAHIMI Idrisse', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.8, phone: '06 60 36 77 14', lat: 34.0622, lng: -6.7925 },
  { id: 61, name: 'EL MAHDI Tabit', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 69 62 61 64', lat: 34.0253, lng: -6.7929 },
  { id: 62, name: 'OUAAZIZ Hassan', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.9, phone: '06 65 45 63 90', lat: 34.0199, lng: -6.8252 },
  { id: 63, name: 'CHERKAOUI Mohammed', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 66 31 44 95', lat: 34.0754, lng: -6.8094 },
  { id: 64, name: 'HDIDO Driss', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.7, phone: '0664 02 76 20', lat: 34.0113, lng: -6.8277 },
  { id: 65, name: 'LEMRABET Anas', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '06 65 19 90 76', lat: 34.0135, lng: -6.839 },
  { id: 66, name: 'MOUNIR Rachid', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 13 68 72 23', lat: 34.0306, lng: -6.8268 },
  { id: 67, name: 'DAOUDI Aziz', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Rahma', rating: 4.9, phone: '06 65 46 94 39', lat: 34.0362, lng: -6.8286 },
  { id: 68, name: 'OUAAYAN Khalid', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Karima', rating: 4.5, phone: '06 62 73 29 48', lat: 34.0722, lng: -6.8239 },
  { id: 69, name: 'EL KLAYER Abdeljabar', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 68 10 02', lat: 34.072, lng: -6.8392 },
  { id: 70, name: 'ZHAR Abdellah', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.8, phone: '06 61 76 54 76', lat: 34.004, lng: -6.8306 },
  { id: 71, name: 'SAHRAOUI El Houssine', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.6, phone: '06 14 49 45 24', lat: 34.0189, lng: -6.8525 },
  { id: 72, name: 'EL GOUBI Mounir', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Chmaou', rating: 4.9, phone: '06 62 41 38 04 / 06 20 13 48 08', lat: 34.0623, lng: -6.8488 },
  { id: 73, name: 'AL MAHFOUDI Abdelghani', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 70 32 56 10', lat: 34.018, lng: -6.8397 },
  { id: 74, name: 'youssef maddahi', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'N 45 rue essaouira sect nahda laayayda', rating: 4.7, phone: '0668277263', lat: 34.0632, lng: -6.7865 },

  // ... (Rest of professionalsData remains unchanged)
];

export const PROFESSIONALS = professionalsData;

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    main_heading: 'Professional Home Services On Demand',
    sub_heading: 'Connect with trusted plumbers, electricians, and painters in Morocco.',
    search_placeholder: 'What service do you need?',
    search_button: 'Search',
    our_services: 'Our Services',
    find_a_pro: 'Find a Professional',
    results_found_one: '1 professional found',
    results_found_other: '{count} professionals found',
    no_pros_found: 'No professionals found matching your criteria.',
    view_profile: 'View Profile',
    filter_by_city: 'Filter by city',
    all_cities: 'All Cities',
    map_title: 'Find Professionals Near You',
    map_select_category_prompt: 'Select a category above to see professionals on the map',
    finding_location: 'Locating...',
    find_near_me: 'Find Near Me',
    nearby_professionals: 'Nearby Professionals',
    distance_km: '{dist} km away',
    login_signup: 'Login / Sign Up',
    post_a_job: 'Post a Job',
    job_board: 'Job Board',
    my_activity: 'My Activity',
    support: 'Support',
    footer_company: 'Company',
    footer_contact: 'Contact Us',
    footer_privacy_policy: 'Privacy Policy',
    footer_usage_guidelines: 'Usage Guidelines',
    all_rights_reserved: 'All rights reserved.',
    previous: 'Previous',
    next: 'Next',
    cant_find_pro: "Can't find the right professional?",
    post_a_job_cta: "Post a Job Request",
    post_job_subtext: "Tell us what you need and receive offers from qualified pros.",
    delete: 'Delete',
    delete_job: 'Delete Job',
    confirm_delete_job: 'Are you sure you want to delete this job?',
    job_deleted: 'Job deleted successfully.',
    manage_jobs: 'Manage Jobs',
    contact_messages: 'Contact Messages',
    // Auth & Profile
    welcome_back: 'Welcome Back',
    create_account: 'Create Your Account',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    logout: 'Logout',
    email_address: 'Email Address',
    password: 'Password',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    role_client: 'Client (Looking for a service)',
    role_provider: 'Provider (Offering a service)',
    // Pricing
    pricing_title: 'Simple, Transparent Pricing',
    pricing_subtitle_1: 'Choose the plan that fits your business needs.',
    pricing_subtitle_2: 'Start growing your client base today.',
    plan_standard_name: 'Standard Plan',
    plan_standard_desc: 'Perfect for getting started.',
    plan_standard_feature_1: 'Create a professional profile',
    plan_standard_feature_2: 'List your services in one city',
    plan_standard_feature_3: 'Receive up to 5 job leads/month',
    plan_standard_feature_4: 'Basic support',
    plan_standard_cta: 'Get Started',
    plan_premium_name: 'Premium Plan',
    plan_premium_desc: 'Best for established professionals.',
    plan_premium_feature_1: 'Everything in Standard',
    plan_premium_feature_2: 'List in multiple cities',
    plan_premium_feature_3: 'Unlimited job leads',
    plan_premium_feature_4: 'Priority listing in search',
    plan_premium_feature_5: 'Priority support',
    plan_premium_cta: 'Go Premium',
    price_unit: 'MAD/month',
    plan_featured_badge: 'Most Popular',
    // Payment
    payment_title: 'Upgrade to Premium',
    payment_subtitle: 'Complete your payment to activate your account.',
    payment_holder_name_label: 'Account Holder Name',
    payment_holder_name_value: 'Brikole SARL',
    payment_rib_label: 'RIB (Bank Account Number)',
    payment_reference_label: 'Payment Reference',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'Please make a transfer to the bank account above. Your account will be activated within 24 hours of receipt.',
    payment_done_button: 'I have made the transfer',
    // Job Post
    create_job_request: 'Create Job Request',
    job_title: 'Job Title',
    job_description: 'Description',
    category: 'Category',
    city: 'City',
    budget: 'Budget (MAD)',
    budget_type: 'Budget Type',
    fixed_price: 'Fixed Price',
    negotiable: 'Negotiable',
    submit_job_post: 'Post Job',
    job_posted_successfully: 'Job posted successfully!',
    // Job Board
    open_jobs_near_you: 'Open jobs near you.',
    no_open_jobs: 'No open jobs found.',
    view_details_and_apply: 'View Details & Apply',
    make_an_offer: 'Make an Offer',
    your_offer: 'Your Offer (MAD)',
    optional_message: 'Message (Optional)',
    submit_offer: 'Submit Offer',
    offer_submitted: 'Offer submitted successfully!',
    // My Activity
    my_jobs: 'My Jobs',
    my_offers: 'My Offers',
    view_offers: 'View Offers',
    offers_received: 'Offers Received',
    job_awarded: 'Job Awarded',
    contact_provider_at: 'Contact provider at: {phone}',
    no_offers_yet: 'No offers yet.',
    accept_offer: 'Accept Offer',
    offer_accepted: 'Offer Accepted',
    offer_rejected: 'Offer Rejected',
    offer_pending: 'Pending',
    // Contact & Support
    contact_us_title: 'Contact Us',
    contact_us_subtitle: 'We are here to help. Send us a message.',
    your_name: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    send_message: 'Send Message',
    message_sent_success: 'Message sent successfully!',
    my_tickets: 'My Support Tickets',
    create_new_ticket: 'Create New Ticket',
    no_tickets_found: 'No support tickets found.',
    back_to_tickets: 'Back to Tickets',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    submit_ticket: 'Submit Ticket',
    replies: 'Replies',
    add_reply: 'Add a reply...',
    no_new_messages: 'No new messages.',
    no_archived_messages: 'No archived messages.',
    show_new: 'Show New',
    show_archived: 'Show Archived',
    archive: 'Archive',
    // Static Pages
    privacy_policy_title: 'Privacy Policy',
    last_updated: 'Last Updated:',
    privacy_h2_intro: '1. Introduction',
    privacy_p_intro: 'Welcome to Brikole. We respect your privacy and are committed to protecting your personal data.',
    privacy_h2_info_collect: '2. Information We Collect',
    privacy_p_info_collect: 'We may collect various types of information, including:',
    privacy_li_personal_data_title: 'Personal Data:',
    privacy_li_personal_data_desc: 'Name, email, phone number, etc.',
    privacy_li_usage_data_title: 'Usage Data:',
    privacy_li_usage_data_desc: 'How you interact with our service.',
    privacy_li_geolocation_title: 'Geolocation:',
    privacy_li_geolocation_desc: 'To find nearby professionals.',
    privacy_h2_how_we_use: '3. How We Use Your Information',
    privacy_p_how_we_use: 'We use your data to:',
    privacy_li_use_1: 'Provide and maintain our Service',
    privacy_li_use_2: 'Notify you about changes',
    privacy_li_use_3: 'Allow interactive features',
    privacy_li_use_4: 'Provide customer support',
    privacy_li_use_5: 'Gather analysis to improve',
    privacy_li_use_6: 'Monitor usage',
    privacy_li_use_7: 'Detect and prevent technical issues',
    privacy_h2_disclosure: '4. Disclosure of Data',
    privacy_p_disclosure: 'We may disclose your personal data in good faith belief that such action is necessary to:',
    privacy_li_disclosure_1_title: 'Legal Obligation:',
    privacy_li_disclosure_1_desc: 'To comply with a legal obligation.',
    privacy_li_disclosure_2_title: 'Protection:',
    privacy_li_disclosure_2_desc: 'To protect and defend the rights or property of Brikole.',
    privacy_h2_security: '5. Security of Data',
    privacy_p_security: 'The security of your data is important to us, but remember that no method of transmission over the Internet is 100% secure.',
    privacy_h2_changes: '6. Changes to This Policy',
    privacy_p_changes: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
    privacy_h2_contact: '7. Contact Us',
    privacy_p_contact: 'If you have any questions about this Privacy Policy, please contact us.',
    
    guidelines_title: 'Usage Guidelines',
    effective_date: 'Effective Date:',
    guidelines_h2_intro: 'Introduction',
    guidelines_p_intro: 'These guidelines are designed to ensure a safe and positive experience for all users of Brikole.',
    guidelines_h2_for_clients: 'For Clients',
    guidelines_li_client_1_title: 'Accurate Information:',
    guidelines_li_client_1_desc: 'Provide clear and accurate details about the job.',
    guidelines_li_client_2_title: 'Respect:',
    guidelines_li_client_2_desc: 'Treat service providers with respect and courtesy.',
    guidelines_li_client_3_title: 'Safety:',
    guidelines_li_client_3_desc: 'Ensure a safe working environment for the provider.',
    guidelines_li_client_4_title: 'Payment:',
    guidelines_li_client_4_desc: 'Agree on payment terms clearly before work begins.',
    guidelines_h2_for_providers: 'For Service Providers',
    guidelines_li_provider_1_title: 'Professionalism:',
    guidelines_li_provider_1_desc: 'Maintain high standards of workmanship and conduct.',
    guidelines_li_provider_2_title: 'Punctuality:',
    guidelines_li_provider_2_desc: 'Arrive on time for appointments.',
    guidelines_li_provider_3_title: 'Transparency:',
    guidelines_li_provider_3_desc: 'Be transparent about pricing and services.',
    guidelines_li_provider_4_title: 'Compliance:',
    guidelines_li_provider_4_desc: 'Comply with all local laws and regulations.',
    guidelines_li_provider_5_title: 'Quality:',
    guidelines_li_provider_5_desc: 'Ensure the quality of materials and work.',
    guidelines_h2_prohibited: 'Prohibited Activities',
    guidelines_p_prohibited: 'The following activities are strictly prohibited:',
    guidelines_li_prohibited_1: 'Fraudulent or misleading behavior.',
    guidelines_li_prohibited_2: 'Harassment or hate speech.',
    guidelines_li_prohibited_3: 'Posting illegal or dangerous content.',
    guidelines_li_prohibited_4: 'Spamming or soliciting unrelated services.',
    guidelines_li_prohibited_5: 'Creating fake accounts or reviews.',
    guidelines_h2_enforcement: 'Enforcement',
    guidelines_p_enforcement: 'Violations of these guidelines may result in account suspension or termination.',
  },
  fr: {
    main_heading: 'Services à Domicile Professionnels à la Demande',
    sub_heading: 'Connectez-vous avec des plombiers, électriciens et peintres de confiance au Maroc.',
    search_placeholder: 'De quel service avez-vous besoin ?',
    search_button: 'Rechercher',
    our_services: 'Nos Services',
    find_a_pro: 'Trouver un Professionnel',
    results_found_one: '1 professionnel trouvé',
    results_found_other: '{count} professionnels trouvés',
    no_pros_found: 'Aucun professionnel trouvé correspondant à vos critères.',
    view_profile: 'Voir le Profil',
    filter_by_city: 'Filtrer par ville',
    all_cities: 'Toutes les villes',
    map_title: 'Trouver des Professionnels près de chez vous',
    map_select_category_prompt: 'Sélectionnez une catégorie ci-dessus pour voir les professionnels sur la carte',
    finding_location: 'Localisation...',
    find_near_me: 'Trouver près de moi',
    nearby_professionals: 'Professionnels à proximité',
    distance_km: 'À {dist} km',
    login_signup: 'Connexion / Inscription',
    post_a_job: 'Publier une annonce',
    job_board: 'Offres d\'emploi',
    my_activity: 'Mon Activité',
    support: 'Support',
    footer_company: 'Entreprise',
    footer_contact: 'Contactez-nous',
    footer_privacy_policy: 'Politique de Confidentialité',
    footer_usage_guidelines: 'Conditions d\'utilisation',
    all_rights_reserved: 'Tous droits réservés.',
    previous: 'Précédent',
    next: 'Suivant',
    cant_find_pro: "Vous ne trouvez pas le bon professionnel ?",
    post_a_job_cta: "Publier une demande",
    post_job_subtext: "Dites-nous ce dont vous avez besoin et recevez des offres.",
    delete: 'Supprimer',
    delete_job: 'Supprimer l\'annonce',
    confirm_delete_job: 'Êtes-vous sûr de vouloir supprimer cette annonce ?',
    job_deleted: 'Annonce supprimée avec succès.',
    manage_jobs: 'Gérer les Annonces',
    contact_messages: 'Messages de Contact',
    // Auth & Profile
    welcome_back: 'Bon retour',
    create_account: 'Créer votre compte',
    sign_in: 'Se connecter',
    sign_up: 'S\'inscrire',
    logout: 'Déconnexion',
    email_address: 'Adresse Email',
    password: 'Mot de passe',
    full_name: 'Nom Complet',
    phone_number: 'Numéro de Téléphone',
    role_client: 'Client (Je cherche un service)',
    role_provider: 'Prestataire (Je propose un service)',
     // Pricing
    pricing_title: 'Tarification Simple et Transparente',
    pricing_subtitle_1: 'Choisissez le plan adapté à vos besoins.',
    pricing_subtitle_2: 'Commencez à développer votre clientèle aujourd\'hui.',
    plan_standard_name: 'Plan Standard',
    plan_standard_desc: 'Parfait pour débuter.',
    plan_standard_feature_1: 'Créer un profil professionnel',
    plan_standard_feature_2: 'Lister vos services dans une ville',
    plan_standard_feature_3: 'Recevoir jusqu\'à 5 offres/mois',
    plan_standard_feature_4: 'Support basique',
    plan_standard_cta: 'Commencer',
    plan_premium_name: 'Plan Premium',
    plan_premium_desc: 'Idéal pour les professionnels établis.',
    plan_premium_feature_1: 'Tout dans le plan Standard',
    plan_premium_feature_2: 'Lister dans plusieurs villes',
    plan_premium_feature_3: 'Offres illimitées',
    plan_premium_feature_4: 'Priorité dans les recherches',
    plan_premium_feature_5: 'Support prioritaire',
    plan_premium_cta: 'Passer Premium',
    price_unit: 'MAD/mois',
    plan_featured_badge: 'Le Plus Populaire',
    // Payment
    payment_title: 'Passer à Premium',
    payment_subtitle: 'Effectuez votre paiement pour activer votre compte.',
    payment_holder_name_label: 'Nom du Titulaire du Compte',
    payment_holder_name_value: 'Brikole SARL',
    payment_rib_label: 'RIB (Numéro de Compte Bancaire)',
    payment_reference_label: 'Référence de Paiement',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'Veuillez effectuer un virement sur le compte bancaire ci-dessus. Votre compte sera activé dans les 24 heures suivant la réception.',
    payment_done_button: 'J\'ai effectué le virement',
    // Job Post
    create_job_request: 'Créer une demande',
    job_title: 'Titre de la demande',
    job_description: 'Description',
    category: 'Catégorie',
    city: 'Ville',
    budget: 'Budget (MAD)',
    budget_type: 'Type de Budget',
    fixed_price: 'Prix Fixe',
    negotiable: 'Négociable',
    submit_job_post: 'Publier la demande',
    job_posted_successfully: 'Demande publiée avec succès !',
    // Job Board
    open_jobs_near_you: 'Offres disponibles près de chez vous.',
    no_open_jobs: 'Aucune offre disponible.',
    view_details_and_apply: 'Voir Détails & Postuler',
    make_an_offer: 'Faire une offre',
    your_offer: 'Votre Offre (MAD)',
    optional_message: 'Message (Optionnel)',
    submit_offer: 'Soumettre l\'offre',
    offer_submitted: 'Offre soumise avec succès !',
    // My Activity
    my_jobs: 'Mes Demandes',
    my_offers: 'Mes Offres',
    view_offers: 'Voir les Offres',
    offers_received: 'Offres Reçues',
    job_awarded: 'Attribué',
    contact_provider_at: 'Contacter le prestataire au : {phone}',
    no_offers_yet: 'Aucune offre pour le moment.',
    accept_offer: 'Accepter l\'offre',
    offer_accepted: 'Offre Acceptée',
    offer_rejected: 'Offre Rejetée',
    offer_pending: 'En Attente',
     // Contact & Support
    contact_us_title: 'Contactez-nous',
    contact_us_subtitle: 'Nous sommes là pour vous aider.',
    your_name: 'Votre Nom',
    subject: 'Sujet',
    message: 'Message',
    send_message: 'Envoyer le message',
    message_sent_success: 'Message envoyé avec succès !',
    my_tickets: 'Mes Tickets Support',
    create_new_ticket: 'Créer un Nouveau Ticket',
    no_tickets_found: 'Aucun ticket de support trouvé.',
    back_to_tickets: 'Retour aux Tickets',
    priority: 'Priorité',
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    submit_ticket: 'Soumettre le Ticket',
    replies: 'Réponses',
    add_reply: 'Ajouter une réponse...',
    no_new_messages: 'Pas de nouveaux messages.',
    no_archived_messages: 'Pas de messages archivés.',
    show_new: 'Voir Nouveaux',
    show_archived: 'Voir Archivés',
    archive: 'Archiver',
    // Static Pages
    privacy_policy_title: 'Politique de Confidentialité',
    last_updated: 'Dernière mise à jour :',
    privacy_h2_intro: '1. Introduction',
    privacy_p_intro: 'Bienvenue sur Brikole. Nous respectons votre vie privée et nous engageons à protéger vos données personnelles.',
    privacy_h2_info_collect: '2. Informations que nous collectons',
    privacy_p_info_collect: 'Nous pouvons collecter différents types d\'informations, notamment :',
    privacy_li_personal_data_title: 'Données Personnelles :',
    privacy_li_personal_data_desc: 'Nom, email, numéro de téléphone, etc.',
    privacy_li_usage_data_title: 'Données d\'Utilisation :',
    privacy_li_usage_data_desc: 'Comment vous interagissez avec notre service.',
    privacy_li_geolocation_title: 'Géolocalisation :',
    privacy_li_geolocation_desc: 'Pour trouver des professionnels à proximité.',
    privacy_h2_how_we_use: '3. Comment nous utilisons vos informations',
    privacy_p_how_we_use: 'Nous utilisons vos données pour :',
    privacy_li_use_1: 'Fournir et maintenir notre Service',
    privacy_li_use_2: 'Vous informer des changements',
    privacy_li_use_3: 'Permettre des fonctionnalités interactives',
    privacy_li_use_4: 'Fournir un support client',
    privacy_li_use_5: 'Recueillir des analyses pour améliorer',
    privacy_li_use_6: 'Surveiller l\'utilisation',
    privacy_li_use_7: 'Détecter et prévenir les problèmes techniques',
    privacy_h2_disclosure: '4. Divulgation des données',
    privacy_p_disclosure: 'Nous pouvons divulguer vos données personnelles si nous croyons de bonne foi que cela est nécessaire pour :',
    privacy_li_disclosure_1_title: 'Obligation Légale :',
    privacy_li_disclosure_1_desc: 'Se conformer à une obligation légale.',
    privacy_li_disclosure_2_title: 'Protection :',
    privacy_li_disclosure_2_desc: 'Protéger et défendre les droits ou la propriété de Brikole.',
    privacy_h2_security: '5. Sécurité des données',
    privacy_p_security: 'La sécurité de vos données est importante pour nous, mais rappelez-vous qu\'aucune méthode de transmission sur Internet n\'est sécurisée à 100 %.',
    privacy_h2_changes: '6. Modifications de cette politique',
    privacy_p_changes: 'Nous pouvons mettre à jour notre politique de confidentialité de temps à autre. Nous vous informerons de tout changement en publiant la nouvelle politique sur cette page.',
    privacy_h2_contact: '7. Contactez-nous',
    privacy_p_contact: 'Si vous avez des questions concernant cette politique de confidentialité, veuillez nous contacter.',
    
    guidelines_title: 'Conditions d\'utilisation',
    effective_date: 'Date d\'entrée en vigueur :',
    guidelines_h2_intro: 'Introduction',
    guidelines_p_intro: 'Ces directives sont conçues pour garantir une expérience sûre et positive pour tous les utilisateurs de Brikole.',
    guidelines_h2_for_clients: 'Pour les Clients',
    guidelines_li_client_1_title: 'Informations Précises :',
    guidelines_li_client_1_desc: 'Fournissez des détails clairs et précis sur le travail.',
    guidelines_li_client_2_title: 'Respect :',
    guidelines_li_client_2_desc: 'Traitez les prestataires de services avec respect et courtoisie.',
    guidelines_li_client_3_title: 'Sécurité :',
    guidelines_li_client_3_desc: 'Assurez un environnement de travail sûr pour le prestataire.',
    guidelines_li_client_4_title: 'Paiement :',
    guidelines_li_client_4_desc: 'Convenez clairement des modalités de paiement avant le début des travaux.',
    guidelines_h2_for_providers: 'Pour les Prestataires',
    guidelines_li_provider_1_title: 'Professionnalisme :',
    guidelines_li_provider_1_desc: 'Maintenez des normes élevées de travail et de conduite.',
    guidelines_li_provider_2_title: 'Ponctualité :',
    guidelines_li_provider_2_desc: 'Arrivez à l\'heure aux rendez-vous.',
    guidelines_li_provider_3_title: 'Transparence :',
    guidelines_li_provider_3_desc: 'Soyez transparent sur les prix et les services.',
    guidelines_li_provider_4_title: 'Conformité :',
    guidelines_li_provider_4_desc: 'Respectez toutes les lois et réglementations locales.',
    guidelines_li_provider_5_title: 'Qualité :',
    guidelines_li_provider_5_desc: 'Assurez la qualité des matériaux et du travail.',
    guidelines_h2_prohibited: 'Activités Interdites',
    guidelines_p_prohibited: 'Les activités suivantes sont strictement interdites :',
    guidelines_li_prohibited_1: 'Comportement frauduleux ou trompeur.',
    guidelines_li_prohibited_2: 'Harcèlement ou discours haineux.',
    guidelines_li_prohibited_3: 'Publication de contenu illégal ou dangereux.',
    guidelines_li_prohibited_4: 'Spam ou sollicitation de services non liés.',
    guidelines_li_prohibited_5: 'Création de faux comptes ou avis.',
    guidelines_h2_enforcement: 'Application',
    guidelines_p_enforcement: 'La violation de ces directives peut entraîner la suspension ou la résiliation du compte.',
  },
  ar: {
    main_heading: 'خدمات منزلية احترافية عند الطلب',
    sub_heading: 'تواصل مع سباكين وكهربائيين وصباغين موثوقين في المغرب.',
    search_placeholder: 'ما هي الخدمة التي تحتاجها؟',
    search_button: 'بحث',
    our_services: 'خدماتنا',
    find_a_pro: 'اعثر على محترف',
    results_found_one: 'تم العثور على محترف واحد',
    results_found_other: 'تم العثور على {count} محترفين',
    no_pros_found: 'لم يتم العثور على محترفين مطابقين لمعاييرك.',
    view_profile: 'عرض الملف الشخصي',
    filter_by_city: 'تصفية حسب المدينة',
    all_cities: 'كل المدن',
    map_title: 'ابحث عن المحترفين بالقرب منك',
    map_select_category_prompt: 'اختر فئة أعلاه لرؤية المحترفين على الخريطة',
    finding_location: 'جاري تحديد الموقع...',
    find_near_me: 'ابحث بجواري',
    nearby_professionals: 'محترفون بالجوار',
    distance_km: 'على بعد {dist} كم',
    login_signup: 'تسجيل الدخول / الاشتراك',
    post_a_job: 'انشر وظيفة',
    job_board: 'لوحة الوظائف',
    my_activity: 'نشاطي',
    support: 'الدعم',
    footer_company: 'الشركة',
    footer_contact: 'اتصل بنا',
    footer_privacy_policy: 'سياسة الخصوصية',
    footer_usage_guidelines: 'إرشادات الاستخدام',
    all_rights_reserved: 'جميع الحقوق محفوظة.',
    previous: 'السابق',
    next: 'التالي',
    cant_find_pro: "لم تجد المحترف المناسب؟",
    post_a_job_cta: "انشر طلب عمل",
    post_job_subtext: "أخبرنا بما تحتاجه وتلقى عروضًا من محترفين مؤهلين.",
    delete: 'حذف',
    delete_job: 'حذف الوظيفة',
    confirm_delete_job: 'هل أنت متأكد أنك تريد حذف هذه الوظيفة؟',
    job_deleted: 'تم حذف الوظيفة بنجاح.',
    manage_jobs: 'إدارة الوظائف',
    contact_messages: 'رسائل الاتصال',
    // Auth & Profile
    welcome_back: 'مرحبًا بعودتك',
    create_account: 'أنشئ حسابك',
    sign_in: 'تسجيل الدخول',
    sign_up: 'اشتراك',
    logout: 'تسجيل الخروج',
    email_address: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    full_name: 'الاسم الكامل',
    phone_number: 'رقم الهاتف',
    role_client: 'عميل (أبحث عن خدمة)',
    role_provider: 'مقدم خدمة (أعرض خدمة)',
    // Pricing
    pricing_title: 'أسعار بسيطة وشفافة',
    pricing_subtitle_1: 'اختر الخطة التي تناسب احتياجات عملك.',
    pricing_subtitle_2: 'ابدأ في تنمية قاعدة عملائك اليوم.',
    plan_standard_name: 'الخطة القياسية',
    plan_standard_desc: 'مثالية للبدء.',
    plan_standard_feature_1: 'إنشاء ملف تعريف مهني',
    plan_standard_feature_2: 'إدراج خدماتك في مدينة واحدة',
    plan_standard_feature_3: 'تلقي ما يصل إلى 5 فرص عمل/شهر',
    plan_standard_feature_4: 'دعم أساسي',
    plan_standard_cta: 'ابدأ الآن',
    plan_premium_name: 'الخطة المميزة',
    plan_premium_desc: 'الأفضل للمحترفين الراسخين.',
    plan_premium_feature_1: 'كل شيء في الخطة القياسية',
    plan_premium_feature_2: 'الإدراج في مدن متعددة',
    plan_premium_feature_3: 'فرص عمل غير محدودة',
    plan_premium_feature_4: 'أولوية الظهور في البحث',
    plan_premium_feature_5: 'دعم ذو أولوية',
    plan_premium_cta: 'اشترك في المميزة',
    price_unit: 'درهم/شهر',
    plan_featured_badge: 'الأكثر شيوعًا',
    // Payment
    payment_title: 'الترقية إلى بريميوم',
    payment_subtitle: 'أكمل الدفع لتفعيل حسابك.',
    payment_holder_name_label: 'اسم صاحب الحساب',
    payment_holder_name_value: 'بريكول ش.م.م',
    payment_rib_label: 'رقم التعريف البنكي (RIB)',
    payment_reference_label: 'مرجع الدفع',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'يرجى إجراء تحويل إلى الحساب المصرفي أعلاه. سيتم تفعيل حسابك في غضون 24 ساعة من الاستلام.',
    payment_done_button: 'لقد قمت بالتحويل',
    // Job Post
    create_job_request: 'إنشاء طلب عمل',
    job_title: 'عنوان الوظيفة',
    job_description: 'الوصف',
    category: 'الفئة',
    city: 'المدينة',
    budget: 'الميزانية (درهم)',
    budget_type: 'نوع الميزانية',
    fixed_price: 'سعر ثابت',
    negotiable: 'قابل للتفاوض',
    submit_job_post: 'نشر الوظيفة',
    job_posted_successfully: 'تم نشر الوظيفة بنجاح!',
    // Job Board
    open_jobs_near_you: 'وظائف مفتوحة بالقرب منك.',
    no_open_jobs: 'لا توجد وظائف مفتوحة.',
    view_details_and_apply: 'عرض التفاصيل والتقديم',
    make_an_offer: 'قدم عرضًا',
    your_offer: 'عرضك (درهم)',
    optional_message: 'رسالة (اختياري)',
    submit_offer: 'إرسال العرض',
    offer_submitted: 'تم إرسال العرض بنجاح!',
    // My Activity
    my_jobs: 'وظائفي',
    my_offers: 'عروضي',
    view_offers: 'عرض العروض',
    offers_received: 'العروض المستلمة',
    job_awarded: 'تم الترسية',
    contact_provider_at: 'اتصل بمقدم الخدمة على: {phone}',
    no_offers_yet: 'لا توجد عروض بعد.',
    accept_offer: 'قبول العرض',
    offer_accepted: 'تم قبول العرض',
    offer_rejected: 'تم رفض العرض',
    offer_pending: 'قيد الانتظار',
    // Contact & Support
    contact_us_title: 'اتصل بنا',
    contact_us_subtitle: 'نحن هنا للمساعدة. أرسل لنا رسالة.',
    your_name: 'اسمك',
    subject: 'الموضوع',
    message: 'الرسالة',
    send_message: 'إرسال الرسالة',
    message_sent_success: 'تم إرسال الرسالة بنجاح!',
    my_tickets: 'تذاكر الدعم الخاصة بي',
    create_new_ticket: 'إنشاء تذكرة جديدة',
    no_tickets_found: 'لم يتم العثور على تذاكر دعم.',
    back_to_tickets: 'العودة إلى التذاكر',
    priority: 'الأولوية',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    submit_ticket: 'إرسال التذكرة',
    replies: 'الردود',
    add_reply: 'أضف ردًا...',
    no_new_messages: 'لا توجد رسائل جديدة.',
    no_archived_messages: 'لا توجد رسائل مؤرشفة.',
    show_new: 'عرض الجديد',
    show_archived: 'عرض المؤرشف',
    archive: 'أرشفة',
    // Static Pages
    privacy_policy_title: 'سياسة الخصوصية',
    last_updated: 'آخر تحديث:',
    privacy_h2_intro: '1. مقدمة',
    privacy_p_intro: 'مرحبًا بكم في بريكول. نحن نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية.',
    privacy_h2_info_collect: '2. المعلومات التي نجمعها',
    privacy_p_info_collect: 'قد نجمع أنواعًا مختلفة من المعلومات، بما في ذلك:',
    privacy_li_personal_data_title: 'البيانات الشخصية:',
    privacy_li_personal_data_desc: 'الاسم، البريد الإلكتروني، رقم الهاتف، إلخ.',
    privacy_li_usage_data_title: 'بيانات الاستخدام:',
    privacy_li_usage_data_desc: 'كيفية تفاعلك مع خدمتنا.',
    privacy_li_geolocation_title: 'تحديد الموقع الجغرافي:',
    privacy_li_geolocation_desc: 'للعثور على محترفين بالقرب منك.',
    privacy_h2_how_we_use: '3. كيف نستخدم معلوماتك',
    privacy_p_how_we_use: 'نستخدم بياناتك لـ:',
    privacy_li_use_1: 'توفير وصيانة خدمتنا',
    privacy_li_use_2: 'إعلامك بالتغييرات',
    privacy_li_use_3: 'السماح بالميزات التفاعلية',
    privacy_li_use_4: 'تقديم الدعم للعملاء',
    privacy_li_use_5: 'جمع التحليلات للتحسين',
    privacy_li_use_6: 'مراقبة الاستخدام',
    privacy_li_use_7: 'كشف ومنع المشاكل التقنية',
    privacy_h2_disclosure: '4. الكشف عن البيانات',
    privacy_p_disclosure: 'قد نكشف عن بياناتك الشخصية بحسن نية إذا كان هذا الإجراء ضروريًا لـ:',
    privacy_li_disclosure_1_title: 'التزام قانوني:',
    privacy_li_disclosure_1_desc: 'للامتثال لالتزام قانوني.',
    privacy_li_disclosure_2_title: 'الحماية:',
    privacy_li_disclosure_2_desc: 'لحماية والدفاع عن حقوق أو ممتلكات بريكول.',
    privacy_h2_security: '5. أمن البيانات',
    privacy_p_security: 'أمن بياناتك مهم بالنسبة لنا، ولكن تذكر أنه لا توجد وسيلة نقل عبر الإنترنت آمنة بنسبة 100٪.',
    privacy_h2_changes: '6. تغييرات على هذه السياسة',
    privacy_p_changes: 'قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنقوم بإعلامك بأي تغييرات عن طريق نشر السياسة الجديدة على هذه الصفحة.',
    privacy_h2_contact: '7. اتصل بنا',
    privacy_p_contact: 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا.',

    guidelines_title: 'إرشادات الاستخدام',
    effective_date: 'تاريخ السريان:',
    guidelines_h2_intro: 'مقدمة',
    guidelines_p_intro: 'تم تصميم هذه الإرشادات لضمان تجربة آمنة وإيجابية لجميع مستخدمي بريكول.',
    guidelines_h2_for_clients: 'للعملاء',
    guidelines_li_client_1_title: 'معلومات دقيقة:',
    guidelines_li_client_1_desc: 'قدم تفاصيل واضحة ودقيقة حول الوظيفة.',
    guidelines_li_client_2_title: 'الاحترام:',
    guidelines_li_client_2_desc: 'عامل مقدمي الخدمات باحترام وكياسة.',
    guidelines_li_client_3_title: 'السلامة:',
    guidelines_li_client_3_desc: 'ضمان بيئة عمل آمنة لمقدم الخدمة.',
    guidelines_li_client_4_title: 'الدفع:',
    guidelines_li_client_4_desc: 'اتفق بوضوح على شروط الدفع قبل بدء العمل.',
    guidelines_h2_for_providers: 'لمقدمي الخدمات',
    guidelines_li_provider_1_title: 'الاحترافية:',
    guidelines_li_provider_1_desc: 'الحفاظ على معايير عالية من العمل والسلوك.',
    guidelines_li_provider_2_title: 'الالتزام بالمواعيد:',
    guidelines_li_provider_2_desc: 'الوصول في الوقت المحدد للمواعيد.',
    guidelines_li_provider_3_title: 'الشفافية:',
    guidelines_li_provider_3_desc: 'كن شفافًا بشأن الأسعار والخدمات.',
    guidelines_li_provider_4_title: 'الامتثال:',
    guidelines_li_provider_4_desc: 'الامتثال لجميع القوانين واللوائح المحلية.',
    guidelines_li_provider_5_title: 'الجودة:',
    guidelines_li_provider_5_desc: 'ضمان جودة المواد والعمل.',
    guidelines_h2_prohibited: 'الأنشطة المحظورة',
    guidelines_p_prohibited: 'يُحظر تمامًا الأنشطة التالية:',
    guidelines_li_prohibited_1: 'السلوك الاحتيالي أو المضلل.',
    guidelines_li_prohibited_2: 'التحرش أو خطاب الكراهية.',
    guidelines_li_prohibited_3: 'نشر محتوى غير قانوني أو خطير.',
    guidelines_li_prohibited_4: 'إرسال البريد العشوائي أو التماس خدمات غير ذات صلة.',
    guidelines_li_prohibited_5: 'إنشاء حسابات أو مراجعات وهمية.',
    guidelines_h2_enforcement: 'التنفيذ',
    guidelines_p_enforcement: 'قد تؤدي انتهاكات هذه الإرشادات إلى تعليق الحساب أو إنهائه.',
  },
};
