
import { ServiceCategory, Language, TranslationSet, Professional } from './types';
import { Wrench, PlugZap, PaintRoller, Droplets, Hammer, Sofa } from './components/icons';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'ar', name: 'العربية' },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    icon: Droplets,
    name: {
      en: 'Plumbing',
      fr: 'Plomberie',
      ar: 'السباكة',
    },
  },
  {
    id: 'electrical',
    icon: PlugZap,
    name: {
      en: 'Electrical',
      fr: 'Électricité',
      ar: 'الكهرباء',
    },
  },
  {
    id: 'painting',
    icon: PaintRoller,
    name: {
      en: 'Painting',
      fr: 'Peinture',
      ar: 'الدهان',
    },
  },
  {
    id: 'carpentry',
    icon: Hammer,
    name: {
      en: 'Carpentry',
      fr: 'Menuiserie',
      ar: 'النجارة',
    },
  },
   {
    id: 'general_repair',
    icon: Wrench,
    name: {
      en: 'General Repair',
      fr: 'Réparation Générale',
      ar: 'إصلاحات عامة',
    },
  },
  {
    id: 'assembly',
    icon: Sofa,
    name: {
      en: 'Furniture Assembly',
      fr: 'Montage de Meubles',
      ar: 'تركيب الأثاث',
    },
  },
];

const professionalsData: Professional[] = [
  // Casablanca Plumbers
  { id: 1, name: 'ELWARDI Hassan', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Avenue Bordeaux', rating: 4.8, phone: '06 53 69 87 70', lat: 33.5854, lng: -7.6366 },
  { id: 2, name: 'EDDAIF Abdelmajid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.9, phone: '06 68 17 27 07', lat: 33.5862, lng: -7.5912 },
  { id: 3, name: 'FADLI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 42 75 38 93', lat: 33.528, lng: -7.6186 },
  { id: 4, name: 'KOKAJI Simohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.6, phone: '06 65 83 19 61', lat: 33.595, lng: -7.6338 },
  { id: 5, name: 'ELGARMA Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 75 47 64 51', lat: 33.5651, lng: -7.6309 },
  { id: 6, name: 'MOURAD Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.7, phone: '06 14 63 87 87', lat: 33.5831, lng: -7.5682 },
  { id: 7, name: 'AMROUG Hamid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '06 10 88 35 16', lat: 33.618, lng: -7.551 },
  { id: 8, name: 'ARGAZ Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Sebaa', rating: 4.8, phone: '06 00 57 29 47', lat: 33.5947, lng: -7.5619 },
  { id: 9, name: 'RAOUF Hicham', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.6, phone: '06 62 16 68 34', lat: 33.5943, lng: -7.5578 },
  { id: 10, name: 'ENNAKRI Abdelhadi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.7, phone: '06 15 74 15 33', lat: 33.578, lng: -7.5401 },
  { id: 11, name: 'BEL KHADRASSI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '06 67 26 85 15', lat: 33.565, lng: -7.5913 },
  { id: 12, name: 'BEN ARBIA Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '06 66 30 30 44', lat: 33.5283, lng: -7.6183 },
  { id: 13, name: 'AL MISRA Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Moumen', rating: 4.8, phone: '06 71 46 18 99', lat: 33.606, lng: -7.6187 },
  { id: 14, name: 'SENHAJI Abdennabi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Harrouda', rating: 4.7, phone: '06 62 01 74 59', lat: 33.5746, lng: -7.5856 },
  { id: 15, name: 'AIT BRAHIM Mohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 41 71 56 82', lat: 33.5655, lng: -7.5943 },
  { id: 16, name: 'ENNAINI Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.6, phone: '06 38 11 65 78', lat: 33.591, lng: -7.604 },
  { id: 17, name: 'ELASSOULI Houcine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.8, phone: '06 61 85 20 20', lat: 33.5768, lng: -7.6256 },
  { id: 18, name: 'KECHAF Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.5, phone: '06 63 59 06 10', lat: 33.5606, lng: -7.6072 },
  { id: 19, name: 'ERAYHANI Khalid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 64 74 33 46', lat: 33.582, lng: -7.6369 },
  { id: 20, name: 'AHBARI Mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.9, phone: '06 60 95 89 83', lat: 33.5638, lng: -7.5501 },
  { id: 21, name: 'EL OUAFI Yassine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.6, phone: '06 71 13 56 07', lat: 33.5752, lng: -7.636 },
  { id: 22, name: 'ALAMI Karim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.8, phone: '06 69 87 45 21', lat: 33.606, lng: -7.6201 },
  { id: 23, name: 'abdessamad biad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '0614149221', lat: 33.5414, lng: -7.5852 },
  { id: 24, name: 'HADDAD Ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '3, rue Ibrahim Hafid -ex Chateaubriand, Q. Gauthier - 20060', rating: 4.7, phone: '0522664088', lat: 33.598, lng: -7.5492 },
  { id: 25, name: 'nachit ayoub', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'derb el wydad blok 511 n 748 hay hassani', rating: 4.9, phone: '0630113133', lat: 33.5358, lng: -7.5755 },
  { id: 26, name: 'Selmouni Brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Maarif', rating: 4.6, phone: '0670398387', lat: 33.6191, lng: -7.5794 },
  { id: 27, name: 'El Fissaoui Youness', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '61 rue 1 khalil 2 la villette', rating: 4.8, phone: '0678636249', lat: 33.5678, lng: -7.6267 },
  { id: 28, name: 'SOKTRA', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '9, Bd Abdelmoumen', rating: 4.5, phone: '0655904767', lat: 33.5467, lng: -7.5663 },
  { id: 29, name: 'Youness Boujmad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Hay almasjid rue28 n 9 casa', rating: 4.7, phone: '0662713781', lat: 33.5937, lng: -7.6218 },
  { id: 30, name: 'mabsout abdelfattaj', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Rue 12 imm 6 n 12 residence khaled sekelia hay hassani', rating: 4.9, phone: '0679648647', lat: 33.5979, lng: -7.5422 },
  { id: 31, name: 'maddah mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'anassi al bernossi', rating: 4.6, phone: '0699901535', lat: 33.565, lng: -7.6166 },
  { id: 32, name: 'Aitbelahsen ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'bloc saada 301 bd grande ceinture N 367', rating: 4.8, phone: '0660565036', lat: 33.6171, lng: -7.6322 },
  { id: 33, name: 'ibra brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '0665426598', lat: 33.6186, lng: -7.6164 },
  
  // Rabat Plumbers
  { id: 34, name: 'ENNASRAOUI Jamal', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.7, phone: '06 41 14 66 24', lat: 34.0256, lng: -6.8123 },
  { id: 35, name: 'SMOUNI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 65 23 40 13/06 66 11 42 64', lat: 34.0416, lng: -6.8299 },
  { id: 36, name: 'SOUHADI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.6, phone: '06 22 68 47 03/06 77 92 19 67', lat: 34.0041, lng: -6.8839 },
  { id: 37, name: 'BENDADNI Bendadani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.5, phone: '05 37 69 91 93', lat: 34.0621, lng: -6.8378 },
  { id: 38, name: 'MBOUKI Omar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.9, phone: '06 73 30 49 49', lat: 34.0689, lng: -6.8208 },
  { id: 39, name: 'AADIM Youssef', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 74 37 23 73', lat: 33.971, lng: -6.882 },
  { id: 40, name: 'BOU INAN Abdelghani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Yacoub Al Mansour', rating: 4.8, phone: '06 65 06 66 18 / 06 35 46 39 75', lat: 34.0536, lng: -6.839 },
  { id: 41, name: 'AL MOHANDISS Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.6, phone: '06 70 94 05 83', lat: 34.0436, lng: -6.8211 },
  { id: 42, name: 'EL AMRANI Karim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 68 62 71 73', lat: 33.9928, lng: -6.843 },
  { id: 43, name: 'BEROUMI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.5, phone: '06 22 62 03 58', lat: 34.0534, lng: -6.8041 },
  { id: 44, name: 'KERROUMI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.7, phone: '06 66 08 12 52 / 06 6 1 32 10 42', lat: 34.0135, lng: -6.8872 },
  { id: 45, name: 'EL KALEM Ahmed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.8, phone: '06 63 03 80 73', lat: 34.016, lng: -6.8413 },
  { id: 46, name: 'DRISSAT Elarbi', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.6, phone: '06 68 01 22 03', lat: 34.048, lng: -6.8396 },
  { id: 47, name: 'ERRAZITMI Abdelkabir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 78 34 79 62', lat: 34.062, lng: -6.8406 },
  { id: 48, name: 'EL MAJDOULI Chankaoui', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'L\'Ocean', rating: 4.5, phone: '06 69 03 11 83', lat: 34.0175, lng: -6.831 },
  { id: 49, name: 'MOUNDA Lehcen', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 66 32 53 06', lat: 33.9749, lng: -6.8583 },
  { id: 50, name: 'EL OUAZZANI Abdessamad', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 66 84 41 48', lat: 34.0692, lng: -6.8447 },
  { id: 51, name: 'ERRAMADI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.6, phone: '06 66 01 07 46', lat: 33.9926, lng: -6.8797 },
  { id: 52, name: 'EL ALAOUI Hassan', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 63 88 81 20', lat: 34.0354, lng: -6.8778 },
  { id: 53, name: 'Ahmed Manar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '12 rue de hay riad', rating: 4.5, phone: '06636598541', lat: 34.0123, lng: -6.8837 },
  { id: 54, name: 'hicham chakir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'agdal', rating: 4.7, phone: '0630892791', lat: 34.0189, lng: -6.8436 },
  { id: 55, name: 'samlali youness', serviceId: 'plumbing', serviceCities: ['Rabat', 'Témara'], address: 'masira 1 n 33', rating: 4.8, phone: '0617546262', lat: 33.9754, lng: -6.8741 },
  { id: 56, name: 'Naji Hicham', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N° 470 CYM', rating: 4.6, phone: '0623503918', lat: 33.9877, lng: -6.875 },
  { id: 57, name: 'abdelmotalib ahdaf', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'AV HASSAN II N°24, Cité Almanar DIOUR JAMAA', rating: 4.9, phone: '06 23 47 77 12', lat: 33.9711, lng: -6.8458 },
  { id: 58, name: 'Boucetta Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N 1343 hay el manzah cym', rating: 4.7, phone: '0661735121', lat: 34.0205, lng: -6.8863 },

  // Salé Plumbers
  { id: 59, name: 'EL GOUILI Lahcen', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 03 66 91', lat: 34.0326, lng: -6.8623 },
  { id: 60, name: 'IBRAHIMI Idrisse', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.8, phone: '06 60 36 77 14', lat: 34.0622, lng: -6.7925 },
  { id: 61, name: 'EL MAHDI Tabit', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 69 62 61 64', lat: 34.0253, lng: -6.7929 },
  { id: 62, name: 'OUAAZIZ Hassan', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.9, phone: '06 65 45 63 90', lat: 34.0199, lng: -6.8252 },
  { id: 63, name: 'CHERKAOUI Mohammed', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 66 31 44 95', lat: 34.0754, lng: -6.8094 },
  { id: 64, name: 'HDIDO Driss', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.7, phone: '0664 02 76 20', lat: 34.0113, lng: -6.8277 },
  { id: 65, name: 'LEMRABET Anas', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '06 65 19 90 76', lat: 34.0135, lng: -6.839 },
  { id: 66, name: 'MOUNIR Rachid', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 13 68 72 23', lat: 34.0306, lng: -6.8268 },
  { id: 67, name: 'DAOUDI Aziz', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Rahma', rating: 4.9, phone: '06 65 46 94 39', lat: 34.0362, lng: -6.8286 },
  { id: 68, name: 'OUAAYAN Khalid', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Karima', rating: 4.5, phone: '06 62 73 29 48', lat: 34.0722, lng: -6.8239 },
  { id: 69, name: 'EL KLAYER Abdeljabar', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 68 10 02', lat: 34.072, lng: -6.8392 },
  { id: 70, name: 'ZHAR Abdellah', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.8, phone: '06 61 76 54 76', lat: 34.004, lng: -6.8306 },
  { id: 71, name: 'SAHRAOUI El Houssine', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.6, phone: '06 14 49 45 24', lat: 34.0189, lng: -6.8525 },
  { id: 72, name: 'EL GOUBI Mounir', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Chmaou', rating: 4.9, phone: '06 62 41 38 04 / 06 20 13 48 08', lat: 34.0623, lng: -6.8488 },
  { id: 73, name: 'AL MAHFOUDI Abdelghani', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 70 32 56 10', lat: 34.018, lng: -6.8397 },
  { id: 74, name: 'youssef maddahi', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'N 45 rue essaouira sect nahda laayayda', rating: 4.7, phone: '0668277263', lat: 34.0632, lng: -6.7865 },

  // Marrakech Plumbers
  { id: 75, name: 'mohamed elbakouri', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate, Route Ourika', rating: 4.7, phone: '0660818600', lat: 31.6288, lng: -8.0264 },
  { id: 76, name: 'R.E.S.T.D Travaux divers', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '72 lot zaitouna rue al inab, Mhamid', rating: 4.8, phone: '0660558377', lat: 31.6709, lng: -7.957 },
  { id: 77, name: 'tarik jawad', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'dwar iziki darb lhjam n 491', rating: 4.6, phone: '0662496544', lat: 31.6212, lng: -7.9377 },
  { id: 78, name: 'mohamed hada abid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '147 derb el massi syba', rating: 4.9, phone: '0676140995', lat: 31.6738, lng: -7.9942 },
  { id: 79, name: 'Ste zayd tech Liyazid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Massira', rating: 4.5, phone: '0675712224', lat: 31.6441, lng: -7.9421 },
  { id: 80, name: 'elfajri younes', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.7, phone: '0648998330', lat: 31.5833, lng: -8.0163 },
  { id: 81, name: 'Mohamed Ali', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.8, phone: '0675009697', lat: 31.5947, lng: -8.0069 },
  { id: 82, name: 'Abdslam Kodsi', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Massira, lot les palmies 1 n 552 targa', rating: 4.6, phone: '0654507554 // 0634678590', lat: 31.6293, lng: -8.0298 },
  { id: 83, name: 'rifaai hassan', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'L harakat n 23 tasltant', rating: 4.9, phone: '0676842151', lat: 31.6579, lng: -8.024 },
  { id: 84, name: 'Mourad', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Les portes de Marrakech', rating: 4.7, phone: '0636144800', lat: 31.6416, lng: -7.9868 },
  { id: 85, name: 'EL GOUITI Abdelilah', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.8, phone: '06 63 51 92 35', lat: 31.5975, lng: -7.9388 },
  { id: 86, name: 'DOUKALI Radouane', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.6, phone: '06 70 25 22 42 / 06 00 26 26 41', lat: 31.6521, lng: -7.9625 },
  { id: 87, name: 'CHEMSEDDINE Kamal', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Mhamid', rating: 4.9, phone: '06 61 54 56 46', lat: 31.5866, lng: -8.0055 },
  { id: 88, name: 'MOHAMED Amine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'plombicom', rating: 4.5, phone: '06 99 56 91 21', lat: 31.6163, lng: -8.0163 },
  { id: 89, name: 'MUSTAPHA Mustapha', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Bab doukala arset al ahbasse N49 hay jazouli', rating: 4.7, phone: '06 98 20 85 15', lat: 31.6033, lng: -7.9405 },
  { id: 90, name: 'AIT BEN SALEH Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.8, phone: '0673629584', lat: 31.6373, lng: -7.9416 },
  { id: 91, name: 'ABUMANDIL Khalil', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 66 56 68 76', lat: 31.6111, lng: -7.9538 },
  { id: 92, name: 'JARDI Youness', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.5, phone: '06 68 77 44 36', lat: 31.5833, lng: -7.9959 },
  { id: 93, name: 'BEN CHAKROUNE Abderrahim', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.7, phone: '06 64 38 53 72', lat: 31.6214, lng: -7.9912 },
  { id: 94, name: 'CHALSI Mohammed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.8, phone: '06 71 36 38 20', lat: 31.666, lng: -8.0287 },
  { id: 95, name: 'TIWAN Mounir', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.6, phone: '06 15 26 50 77', lat: 31.6617, lng: -7.939 },
  { id: 96, name: 'IWAHDA Rachid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.9, phone: '06 62 10 68 90', lat: 31.6384, lng: -7.9944 },
  { id: 97, name: 'ERROWAF Hamid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.5, phone: '06 64 24 52 29', lat: 31.6441, lng: -7.9408 },
  { id: 98, name: 'AIT MBAREK Azeddine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.7, phone: '06 64 54 62 98', lat: 31.582, lng: -7.9997 },
  { id: 99, name: 'DRAY Said', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.8, phone: '06 78 26 87 59', lat: 31.5992, lng: -8.0061 },
  { id: 100, name: 'IDRISSI Mohamed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.6, phone: '06 11 77 47 49', lat: 31.6678, lng: -7.9542 },
  { id: 101, name: 'SALAMTI Ibrahim', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 71 23 52 03', lat: 31.6678, lng: -7.9701 },
  { id: 102, name: 'AIT OUDRI Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Douar El Askar', rating: 4.5, phone: '06 61 72 48 45', lat: 31.6703, lng: -7.9984 },
  { id: 103, name: 'MOUTAWAKIL Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Youssoufia', rating: 4.7, phone: '06 71 57 80 34', lat: 31.6657, lng: -8.012 },
  { id: 104, name: 'BOUTOBA Youssef', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.8, phone: '06 77 44 18 24', lat: 31.6111, lng: -8.0195 },
  { id: 105, name: 'OUALD ELHAMRIA Azeddine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.6, phone: '06 10 51 30 12', lat: 31.6448, lng: -8.0062 },
  { id: 106, name: 'MAAROUF Ahmed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 72 64 11 99', lat: 31.6256, lng: -7.9511 },
  { id: 107, name: 'Himmich Said', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Gueliz', rating: 4.8, phone: '0610156881', lat: 31.5997, lng: -7.9818 },
  { id: 108, name: 'ayoub elmadimi', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'sidi youssef ben ali', rating: 4.6, phone: '0674994453', lat: 31.6702, lng: -7.9625 },
  { id: 109, name: 'EL YACOUBI MUSTAPHA', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'MHAMID 9', rating: 4.9, phone: '+212 698208515', lat: 31.6496, lng: -8.006 },
  { id: 110, name: 'Abdelkrim Khlifa', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Madeira 1 -a-N665 3ème étage', rating: 4.7, phone: '0666238327', lat: 31.6648, lng: -7.9944 },
  
  // Tanger Plumbers
  { id: 111, name: 'Amrani Omar', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Marchane centre vile', rating: 4.8, phone: '0676628032', lat: 35.795, lng: -5.8427 },
  { id: 112, name: 'yassin gerroug', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Boukhalf', rating: 4.6, phone: '0610105303', lat: 35.7335, lng: -5.8744 },
  { id: 113, name: 'BEN AMMAR Adnan', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Casabarata', rating: 4.9, phone: '06 63 16 95 63', lat: 35.7997, lng: -5.7992 },
  { id: 114, name: 'HAMDAN Abdessalam', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Casabarata', rating: 4.7, phone: '06 61 75 84 90', lat: 35.7876, lng: -5.7932 },
  { id: 115, name: 'RBICHA Mohamed', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'boukhalef', rating: 4.5, phone: '0600705251', lat: 35.7601, lng: -5.8037 },
  { id: 116, name: 'BAKKALI Abdellatif', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'addoha albalia', rating: 4.8, phone: '0606642791', lat: 35.7946, lng: -5.8546 },
  { id: 117, name: 'Ahmed Joudi', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'jirari 2 rue 63 n 11', rating: 4.9, phone: '0626624408', lat: 35.7327, lng: -5.869 },
  { id: 118, name: 'MOUSTAFA MOUSTAFA', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '0677534144', lat: 35.7176, lng: -5.8344 },
  { id: 119, name: 'anane abdi ila', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'drissia', rating: 4.8, phone: '0610852339', lat: 35.7359, lng: -5.8384 },
  { id: 120, name: 'Khalid Mazoun', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'R albait atique M 12 P 14 Masnana', rating: 4.7, phone: '0636518067', lat: 35.7777, lng: -5.8569 },

  // Agadir Region Plumbers
  { id: 121, name: 'Mestapha Dahraoui', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212601318316', lat: 30.4048, lng: -9.5668 },
  { id: 122, name: 'Youssef Chabi', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.8, phone: '+212610552729', lat: 30.4688, lng: -9.5937 },
  { id: 123, name: 'Zakaria Bila', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212630489659', lat: 30.3845, lng: -9.6433 },
  { id: 124, name: 'Youssef Bouhkoun', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+2120720452055', lat: 30.426, lng: -9.6201 },
  { id: 125, name: 'Azdine Lkoute', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.5, phone: '+212667757744', lat: 30.3995, lng: -9.6385 },
  { id: 126, name: 'Aguersoul Hamid', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Taroudant', 'Tiznit'], address: '', rating: 4.7, phone: '+212655236011', lat: 30.3957, lng: -9.5741 },
  { id: 127, name: 'Abdelhakim Dahbi', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Ouarzazate', 'Taroudant', 'Tiznit'], address: '', rating: 4.8, phone: '+212677554188', lat: 30.4359, lng: -9.5532 },
  { id: 128, name: 'Mohamed Idali', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212781298217', lat: 30.421, lng: -9.5694 },
  { id: 129, name: 'Adil Amghar', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+212667225133', lat: 30.4735, lng: -9.6437 },

  // Casablanca Electricians
  { id: 130, name: 'El Fissaoui Youness', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '61 rue 1 khalil 2 la villette', rating: 4.8, phone: '0678636249', lat: 33.5651, lng: -7.5855 },
  { id: 131, name: 'Edlouali Noureddine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '3 rue 27 derb korea', rating: 4.7, phone: '0707750342', lat: 33.543, lng: -7.632 },
  { id: 132, name: 'Chahbaoui Mhamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'AMAL 01 RUE 22 NR 06 ELBERNOUSSI', rating: 4.9, phone: '0664535754', lat: 33.5598, lng: -7.5492 },
  { id: 133, name: 'Arro Tarik', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Oulfa', rating: 4.6, phone: '+212689400857', lat: 33.5856, lng: -7.5682 },
  { id: 134, name: 'SOKTRA', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '9, Bd Abdelmoumen', rating: 4.8, phone: '0655904767', lat: 33.606, lng: -7.6325 },
  { id: 135, name: 'Youness Boujmad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay almasjid rue28 n 9', rating: 4.5, phone: '0662713781', lat: 33.584, lng: -7.5759 },
  { id: 136, name: 'demni aziz', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.7, phone: '0660893927', lat: 33.5413, lng: -7.6042 },
  { id: 137, name: 'Taloui Ahmed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Darbouazza', rating: 4.9, phone: '0661834481', lat: 33.551, lng: -7.5847 },
  { id: 138, name: 'Mohamed Fathallah', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay oulfa', rating: 4.6, phone: '0615299351', lat: 33.5358, lng: -7.6253 },
  { id: 139, name: 'Selmouni Brahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Maarif', rating: 4.8, phone: '0670398387', lat: 33.5489, lng: -7.6206 },
  { id: 140, name: 'boubker jounaina', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'ain bourja', rating: 4.5, phone: '0613046494', lat: 33.5573, lng: -7.5518 },
  { id: 141, name: 'FARHAT Adio', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay bournazel', rating: 4.7, phone: '0620027992', lat: 33.5878, lng: -7.625 },
  { id: 142, name: 'AMZOUZ Simohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Avenue Bordeaux', rating: 4.9, phone: '06 63 25 17 54', lat: 33.6105, lng: -7.6009 },
  { id: 143, name: 'EL MOAL Khalid', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.6, phone: '06 65 61 03 37', lat: 33.5816, lng: -7.545 },
  { id: 144, name: 'EL HIMER Driss', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '06 61 81 23 96', lat: 33.5968, lng: -7.6217 },
  { id: 145, name: 'KHALFOUNE Abdessamiea', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '06 14 40 10 94', lat: 33.5684, lng: -7.5401 },
  { id: 146, name: 'ERRAMI Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.7, phone: '06 64 55 96 16', lat: 33.5936, lng: -7.5492 },
  { id: 147, name: 'SALMAN Driss', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '06 61 67 05 63', lat: 33.5898, lng: -7.6163 },
  { id: 148, name: 'EL BAHRAOUI Abderrahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Ain Sebaa', rating: 4.6, phone: '06 64 57 56 93', lat: 33.5796, lng: -7.5837 },
  { id: 149, name: 'ECHAHIR Abdelhak', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '06 65 13 12 84', lat: 33.528, lng: -7.6163 },
  { id: 150, name: 'ETTINO Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.5, phone: '06 61 56 63 54', lat: 33.5658, lng: -7.5582 },
  { id: 151, name: 'Echchafi Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Res ALMANZAH GH21 RUE13 IMM6 N°5', rating: 4.7, phone: '+33661379672', lat: 33.5721, lng: -7.6019 },
  { id: 152, name: 'SOUFIAN soufian', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'hay moulay abdellah, rue 116 n 18,ain chock', rating: 4.9, phone: '0673168271', lat: 33.5411, lng: -7.5815 },
  { id: 153, name: 'FAIDAOUI Youssef', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Rue 1 n°56 Hay Essafa Oulfa', rating: 4.6, phone: '06 07 02 03 79', lat: 33.5714, lng: -7.6019 },
  { id: 154, name: 'abdessamad biad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '0614149221', lat: 33.5902, lng: -7.6322 },
  { id: 155, name: 'Lissiri Abdeltif', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bloc 46 n 51 bernnoussi 20600', rating: 4.5, phone: '0640436661', lat: 33.6068, lng: -7.5571 },
  { id: 156, name: 'nachit ayoub', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'derb el wydad blok 511 n 748 hay hassani', rating: 4.7, phone: '0630113133', lat: 33.5962, lng: -7.5921 },
  { id: 157, name: 'MOUSTAID Adil', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 63 22 71 22', lat: 33.5925, lng: -7.5878 },
  { id: 158, name: 'TAGHAZITE Abderrahman', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.6, phone: '06 61 59 44 13', lat: 33.6026, lng: -7.6186 },
  { id: 159, name: 'KASMI Hakim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.8, phone: '06 71 85 74 10', lat: 33.5678, lng: -7.5926 },
  { id: 160, name: 'FIKRI Mohammed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.5, phone: '06 61 88 39 82', lat: 33.5857, lng: -7.5847 },
  { id: 161, name: 'FATHI Adil', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.7, phone: '06 59 78 70 98 / 06 34 61 96 45', lat: 33.5936, lng: -7.604 },
  { id: 162, name: 'ASSANI Jaber', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.9, phone: '06 61 61 74 79', lat: 33.5682, lng: -7.5683 },
  { id: 163, name: 'LAAOUBI Rachid', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.6, phone: '06 77 12 13 67', lat: 33.5513, lng: -7.6366 },
  { id: 164, name: 'EL BAGHDADI Mustapha', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.8, phone: '06 79 16 68 53', lat: 33.6192, lng: -7.5469 },
  { id: 165, name: 'Abdlilah Elouardey', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Projet Hassan 2', rating: 4.8, phone: '0601590914', lat: 33.5359, lng: -7.5511 },
  { id: 166, name: 'sabar taoufik', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'ville errahma N 40 BC 14', rating: 4.6, phone: '0699341812', lat: 33.5623, lng: -7.545 },
  { id: 167, name: 'Ferkani Amine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '0645758372', lat: 33.5973, lng: -7.6253 },
  { id: 168, name: 'CHAHID MEHDI', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '95 Rue 70 mabrouka', rating: 4.7, phone: '0661760902', lat: 33.5878, lng: -7.5412 },
  { id: 169, name: 'KAMAL MAGHNI', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Maarif, HAY WALAA IMM 24 NR 16 TR 18 SECT 02 SIDI MOUMEN', rating: 4.5, phone: '0667098476', lat: 33.5982, lng: -7.5419 },
  { id: 170, name: 'khabar abdelghani', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Oulfa', rating: 4.8, phone: '0667925505', lat: 33.5615, lng: -7.5562 },
  { id: 171, name: 'Amine Fikri', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Rue 22 nr 107 sidi moumen', rating: 4.9, phone: '0762195162', lat: 33.6198, lng: -7.5555 },
  { id: 172, name: 'ibra brahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.6, phone: '0665426598', lat: 33.5855, lng: -7.6323 },
  { id: 173, name: 'Qariouh Omar', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'n 13 app c5 doha 2 jawhara', rating: 4.8, phone: '0652243656', lat: 33.5684, lng: -7.5856 },
  { id: 174, name: 'saidia ayad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.7, phone: '0661877150', lat: 33.5583, lng: -7.6329 },
  { id: 175, name: 'mohamed amine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '6 Rue Al Farabi', rating: 4.9, phone: '0665717495', lat: 33.5415, lng: -7.6346 },
  
  // Agadir Electricians
  { id: 176, name: 'Abderrahim Dekkousse', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212669587771', lat: 30.4132, lng: -9.5694 },
  { id: 177, name: 'Abderrahmane Bougzoul', serviceId: 'electrical', serviceCities: ['Agadir', 'Casablanca', 'Marrakech', 'Rabat', 'Meknès'], address: '', rating: 4.8, phone: '+212637636456', lat: 30.4639, lng: -9.5786 },
  { id: 178, name: 'Mohamed Lechgar', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Taroudant'], address: '', rating: 4.6, phone: '+212624048904', lat: 30.456, lng: -9.6206 },
  { id: 179, name: 'Hassan Belamri', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+212631856901', lat: 30.3957, lng: -9.6231 },
  { id: 180, name: 'Youssef Akrid', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.5, phone: '+212641856573', lat: 30.4674, lng: -9.6366 },
  { id: 181, name: 'Ibrahim Sghiri', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212665388279', lat: 30.4158, lng: -9.5539 },
  { id: 182, name: 'Faycal Lhathouti', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.8, phone: '+212716565030', lat: 30.4293, lng: -9.5701 },
  { id: 183, name: 'EL BOUZKIRI El Houssine', serviceId: 'electrical', serviceCities: ['Agadir'], address: '', rating: 4.6, phone: '06 51 66 10 89', lat: 30.3801, lng: -9.6433 },
  { id: 184, name: 'Mohamed Idali', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212781298217', lat: 30.426, lng: -9.5513 },

  // Tanger Region Electricians
  { id: 185, name: 'abdeljalil fraj', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Mobilité nationale', rating: 4.7, phone: '+212613255547', lat: 35.7979, lng: -5.8451 },
  { id: 186, name: 'Mohamed Rabie Afilal', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212660002973', lat: 35.795, lng: -5.8753 },
  { id: 187, name: 'Said El Houali', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212604702766', lat: 35.7197, lng: -5.8087 },
  { id: 188, name: 'Mohamed Lfilali', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212605607597', lat: 35.7836, lng: -5.7954 },
  { id: 189, name: 'Mohamed Lfilali', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212605607597', lat: 35.7274, lng: -5.8115 },
  { id: 190, name: 'Hamza Lyaakoubi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212766868079', lat: 35.785, lng: -5.8465 },
  { id: 191, name: 'Mohamed Benamti', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212681404339', lat: 35.7299, lng: -5.8447 },
  { id: 192, name: 'said Brico', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'ibiriya', rating: 4.8, phone: '0617675562', lat: 35.7329, lng: -5.8118 },
  { id: 193, name: 'SAIFI Hamza', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'place du 9 Avril', rating: 4.6, phone: '06 03 60 13 19', lat: 35.7538, lng: -5.8504 },
  { id: 194, name: 'AHROUCHE Kamal', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'aéroport tanger ibn batouta', rating: 4.9, phone: '0633976672', lat: 35.7132, lng: -5.8732 },
  { id: 195, name: 'ERBAHI Fouad', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'et les régions', rating: 4.7, phone: '0661770203', lat: 35.793, lng: -5.8155 },
  { id: 196, name: 'anane abdi ila', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'drissia', rating: 4.6, phone: '0610852339', lat: 35.7877, lng: -5.8521 },
  { id: 197, name: 'boazza CHLAHBI', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'medina', rating: 4.9, phone: '0661001001', lat: 35.7725, lng: -5.8516 },
  { id: 198, name: 'Soufiane Hamouche', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Drissia', rating: 4.5, phone: '0630914113', lat: 35.7915, lng: -5.8133 },
  { id: 199, name: 'Alami Said', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Mojamma3 Al Hassani', rating: 4.7, phone: '0657052179', lat: 35.7937, lng: -5.836 },
  { id: 200, name: 'Abderrahim Bakhti', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.8, phone: '+212630679336', lat: 35.7674, lng: -5.8679 },
  { id: 201, name: 'Mougha Mohamed', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212661656175', lat: 35.7289, lng: -5.8291 },
  { id: 202, name: 'Zoheir El Afia', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212649222036', lat: 35.7601, lng: -5.797 },
  { id: 203, name: 'Adil Elmansouri', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.7, phone: '+212648032321', lat: 35.7196, lng: -5.8633 },
  { id: 204, name: 'Anas Elfhail', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212620179135', lat: 35.735, lng: -5.855 },
  { id: 205, name: 'Anas Elfhail', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212620179135', lat: 35.7792, lng: -5.8306 },
  { id: 206, name: 'Abdellah Adjou', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212703230359', lat: 35.7535, lng: -5.8363 },
  { id: 207, name: 'El Mattoute Yassine', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212703802921', lat: 35.7176, lng: -5.8118 },
  { id: 208, name: 'Hassan Nassiri', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212680343879', lat: 35.7483, lng: -5.8115 },
  { id: 209, name: 'Hassan Nassiri', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212680343879', lat: 35.7606, lng: -5.8458 },
  { id: 210, name: 'Oussama El ahmadi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212600013978', lat: 35.722, lng: -5.8614 },
  { id: 211, name: 'Oussama El ahmadi', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212600013978', lat: 35.7197, lng: -5.8152 },
  { id: 212, name: 'Zbir Reda', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212606432807', lat: 35.7777, lng: -5.863 },
  { id: 213, name: 'Jaouad Baazizi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212675619998', lat: 35.7773, lng: -5.8362 },
  { id: 214, name: 'Brahim Lachgar', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212604095719', lat: 35.7573, lng: -5.8711 },
  { id: 215, name: 'Ayoub Didi', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.7, phone: '+212623084540', lat: 35.7797, lng: -5.8601 },
  { id: 216, name: 'Ayoub Didi', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.7, phone: '+212623084540', lat: 35.7314, lng: -5.8306 },
  { id: 217, name: 'Mohsine Bekkari', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212624392615', lat: 35.7461, lng: -5.8458 },
  { id: 218, name: 'Abdelali Er Rosafy', serviceId: 'electrical', serviceCities: ['Tanger', 'Rabat', 'Salé', 'Aïn Aouda', 'Assilah', 'Kenitra', 'Tamesna', 'Témara'], address: '', rating: 4.6, phone: '+212658832494', lat: 35.7925, lng: -5.8055 },
  { id: 219, name: 'Abdelali Er Rosafy', serviceId: 'plumbing', serviceCities: ['Tanger', 'Rabat', 'Salé', 'Aïn Aouda', 'Assilah', 'Kenitra', 'Tamesna', 'Témara'], address: '', rating: 4.6, phone: '+212658832494', lat: 35.7793, lng: -5.8368 },
  { id: 220, name: 'Bilal Melouani', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.9, phone: '+212605765742', lat: 35.7505, lng: -5.8078 },
  { id: 221, name: 'Bilal Melouani', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.9, phone: '+212605765742', lat: 35.7145, lng: -5.8687 },
  { id: 222, name: 'Rachid Hamdane', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212620952285', lat: 35.7259, lng: -5.8197 },
  { id: 223, name: 'Mohamed Chrif Almousafir', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212651455785', lat: 35.7161, lng: -5.8066 },
  { id: 224, name: 'Mohamed Chrif Almousafir', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212651455785', lat: 35.7483, lng: -5.8573 },
  { id: 225, name: 'Otman Migou', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212655988894', lat: 35.7601, lng: -5.8061 },
  { id: 226, name: 'Otman Migou', serviceId: 'plumbing', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212655988894', lat: 35.7533, lng: -5.8037 },
  { id: 227, name: 'Hamza Toudi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212605304755', lat: 35.7481, lng: -5.8752 },
  { id: 228, name: 'Bilal Soufiani', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212631599411', lat: 35.7496, lng: -5.8505 },
  { id: 229, name: 'Bilal Soufiani', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212631599411', lat: 35.7589, lng: -5.8458 },
  { id: 230, name: 'Ayoub Aaryouch', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212665683987', lat: 35.749, lng: -5.855 },
  { id: 231, name: 'Ayoub Aaryouch', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212665683987', lat: 35.7954, lng: -5.8679 },

  // Salé Electricians
  { id: 232, name: 'Adil Jamal', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Hay salam', rating: 4.7, phone: '0667963511', lat: 34.0205, lng: -6.8488 },
  { id: 233, name: 'jalal benhihba', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '0660396712', lat: 34.0456, lng: -6.8286 },
  { id: 234, name: 'benhiba jalal', serviceId: 'electrical', serviceCities: ['Salé'], address: 'bou chouk route de kentra', rating: 4.6, phone: '0660396712', lat: 34.0084, lng: -6.8407 },
  { id: 235, name: 'GRIOUITTE Mohammed', serviceId: 'electrical', serviceCities: ['Salé'], address: '86 Rue Zanata', rating: 4.9, phone: '06 70 28 81 40', lat: 34.0722, lng: -6.7909 },
  { id: 236, name: 'ELarbi DABCH', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Hay Rahma', rating: 4.5, phone: '0697047948', lat: 34.0233, lng: -6.8624 },
  { id: 237, name: 'houssam zeroual', serviceId: 'electrical', serviceCities: ['Salé'], address: 'hay karima 1', rating: 4.8, phone: '0665 700 400', lat: 34.0415, lng: -6.8529 },
  { id: 238, name: 'EL BIYAR Mustapha', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 44 68 80 80', lat: 34.0153, lng: -6.818 },
  { id: 239, name: 'EL ZAAR Ahmad', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 70 76 40 40', lat: 34.0322, lng: -6.8373 },
  { id: 240, name: 'BOUSBAA Bouchaib', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.9, phone: '06 63 54 06 97', lat: 34.0135, lng: -6.8329 },
  { id: 241, name: 'AL MAHFOUDI Abdelghani', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 70 32 56 10', lat: 34.0195, lng: -6.8094 },
  { id: 242, name: 'youssef maddahi', serviceId: 'electrical', serviceCities: ['Salé'], address: 'N 45 rue essaouira sect nahda laayayda salé', rating: 4.8, phone: '0668277263', lat: 34.0113, lng: -6.831 },
  { id: 243, name: 'professionel Redouane', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Karia', rating: 4.7, phone: '0631540218', lat: 34.0329, lng: -6.8488 },
  { id: 244, name: 'tamha mustapha', serviceId: 'electrical', serviceCities: ['Salé'], address: 'hay salam bloc 21 n 559', rating: 4.6, phone: '06 65 00 09 31', lat: 34.0134, lng: -6.8457 },
  { id: 245, name: 'Elgoumiri Mhamed', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Salè medina 5biss', rating: 4.9, phone: '0645264047', lat: 34.0531, lng: -6.8624 },
  { id: 246, name: 'MOUATASSIM Zakariae', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.5, phone: '06 73 74 30 95', lat: 34.0734, lng: -6.8049 },
  { id: 247, name: 'BAKELLA Ibrahim', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '06 65 64 95 84', lat: 34.0622, lng: -6.805 },
  { id: 248, name: 'BRICHE Khalid', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.7, phone: '06 67 28 56 04', lat: 34.0611, lng: -6.853 },
  { id: 249, name: 'AYYACH Noureddine', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Hay Salam', rating: 4.6, phone: '06 62 27 58 11', lat: 34.0766, lng: -6.8202 },
  { id: 250, name: 'NAHHARI Rachid', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.9, phone: '0656 43 28 04', lat: 34.0535, lng: -6.8083 },
  { id: 251, name: 'MENNAN Lehcen', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Hay Rahma', rating: 4.5, phone: '06 62 87 86 65', lat: 34.0205, lng: -6.7865 },
  { id: 252, name: 'BENABO Ahmed', serviceId: 'electrical', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '06 71 95 80 90', lat: 34.0076, lng: -6.8277 },
  { id: 253, name: 'EL BIYAR Khalid', serviceId: 'electrical', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 68 49 49 38', lat: 34.0159, lng: -6.8122 },
  
  // Rabat Electricians
  { id: 254, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Amal 5 n23 cym rabat', rating: 4.7, phone: '0660850116', lat: 34.0264, lng: -6.8267 },
  { id: 255, name: 'Alaoui AHMED', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'OCEAN', rating: 4.8, phone: '0625651190', lat: 33.9961, lng: -6.8524 },
  { id: 256, name: 'sahrawi hassan', serviceId: 'electrical', serviceCities: ['Rabat'], address: '5rue taza rabat hassan', rating: 4.6, phone: '0611269832', lat: 33.9829, lng: -6.8797 },
  { id: 257, name: 'El mrahi mohamed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Amal 2 bloc - D - N°302 CYM rabat', rating: 4.9, phone: '0660850116', lat: 34.0044, lng: -6.8407 },
  { id: 258, name: 'El ghazi Mohamed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Yaakoub el Mansour, C.Y.M rabat', rating: 4.5, phone: '0625651190', lat: 34.0411, lng: -6.8457 },
  { id: 259, name: 'Khalid El biar', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'GR AL YASSAMINE, Bloc 11 , NO 36IMM CHERKAOUI', rating: 4.8, phone: '0668494938', lat: 34.0536, lng: -6.8447 },
  { id: 260, name: 'Tahar Erguig', serviceId: 'electrical', serviceCities: ['Rabat', 'Témara', 'Skhirate'], address: 'mers el kheir skhirate temaraloulalda ouled aliane mers el kheir', rating: 4.7, phone: '0661559782', lat: 34.0355, lng: -6.8778 },
  { id: 261, name: 'Ahmed Ahmed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'CYM', rating: 4.6, phone: '0625651190', lat: 34.0202, lng: -6.8396 },
  { id: 262, name: 'el azzouzi abdessamd', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Tamesna', rating: 4.9, phone: '0602314191', lat: 33.9785, lng: -6.8718 },
  { id: 263, name: 'pro redouane', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'medina', rating: 4.5, phone: '0631540218', lat: 34.037, lng: -6.8525 },
  { id: 264, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Hay elfath', rating: 4.8, phone: '0660850116', lat: 34.0583, lng: -6.8837 },
  { id: 265, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Hay elfath yacoub elmansour', rating: 4.7, phone: '0660850116', lat: 33.993, lng: -6.8569 },
  { id: 266, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Hay elfath yacoub elmansour', rating: 4.6, phone: '0660850116', lat: 34.062, lng: -6.839 },
  { id: 267, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: '23 lot ain atik masira rabat maroc', rating: 4.9, phone: '0660850116', lat: 33.973, lng: -6.8524 },
  { id: 268, name: 'Mohamed Mrahi', serviceId: 'electrical', serviceCities: ['Rabat'], address: '23 lot ain atik masira rabat maroc', rating: 4.5, phone: '0660850116', lat: 33.9722, lng: -6.882 },
  { id: 269, name: 'MOUHSSINE Elmahdi', serviceId: 'electrical', serviceCities: ['Rabat'], address: '9 rue 16 lahbass c y m', rating: 4.8, phone: '0624301149', lat: 34.0315, lng: -6.8378 },
  { id: 270, name: 'EL AZZOUZI Abdessamadf', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'rja fllah', rating: 4.7, phone: '0602314191', lat: 34.0622, lng: -6.8299 },
  { id: 271, name: 'El Khalil Jabrane', serviceId: 'electrical', serviceCities: ['Rabat'], address: '71, Sidi Lahsen El aidi Medina', rating: 4.6, phone: '06 12 49 64 49', lat: 34.0536, lng: -6.8299 },
  { id: 272, name: 'Naji Hicham', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'N° 470 CYM, Rabat', rating: 4.9, phone: '0623503918', lat: 34.0177, lng: -6.8797 },
  { id: 273, name: 'Mohamed Hicham', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Hay el nada', rating: 4.5, phone: '0615188336', lat: 34.0211, lng: -6.8373 },
  { id: 274, name: 'Electricien Simohamed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Avenue Liban, Rabat, Maroc', rating: 4.8, phone: '0667767145', lat: 34.0049, lng: -6.8623 },
  { id: 275, name: 'El Ghazi Ahmed', serviceId: 'electrical', serviceCities: ['Rabat', 'Salé'], address: 'Rabat et sale', rating: 4.7, phone: '0625651190', lat: 34.0031, lng: -6.8407 },
  { id: 276, name: 'Ghazi Ahmed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Agdal', rating: 4.6, phone: '0625651190', lat: 34.0205, lng: -6.8458 },
  { id: 277, name: 'MBARKI Omar', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.9, phone: '06 66 16 06 11', lat: 34.0416, lng: -6.8872 },
  { id: 278, name: 'DASSI Youssef', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.5, phone: '0676 92 74 13', lat: 33.9926, lng: -6.8447 },
  { id: 279, name: 'AARAB Said', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.8, phone: '0537 73 73 62', lat: 34.0286, lng: -6.8123 },
  { id: 280, name: 'JABINI Said', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.7, phone: '06 61 55 74 73', lat: 34.016, lng: -6.8863 },
  { id: 281, name: 'ERRAMI Ahmed', serviceId: 'electrical', serviceCities: ['Rabat'], address: '', rating: 4.6, phone: '06 68 68 43 07', lat: 34.062, lng: -6.8839 },
  { id: 282, name: 'TAMMAM Khalid', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.9, phone: '06 61 89 01 84', lat: 34.0673, lng: -6.843 },
  { id: 283, name: 'EL HRACH Hassan', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.5, phone: '06 67 45 57 96', lat: 34.0671, lng: -6.8299 },
  { id: 284, name: 'ECHARMATTI Abdessalam', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.8, phone: '06 72 86 68 82', lat: 34.0322, lng: -6.8406 },
  { id: 285, name: 'ELWADI Hassan', serviceId: 'electrical', serviceCities: ['Rabat'], address: '', rating: 4.7, phone: '06 13 65 36 92', lat: 34.0248, lng: -6.8208 },
  { id: 286, name: 'ELWARZAZI Omar', serviceId: 'electrical', serviceCities: ['Rabat'], address: '', rating: 4.6, phone: '06 62 45 79 39', lat: 34.053, lng: -6.8041 },
  { id: 287, name: 'HOUBARI Houbari', serviceId: 'electrical', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 11 92 11 29', lat: 34.0041, lng: -6.839 },
  { id: 288, name: 'ETTAHAR Zouhair', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Youssoufia', rating: 4.5, phone: '06 63 71 12 86', lat: 34.048, lng: -6.882 },
  { id: 289, name: 'KHEBBACH Saleh', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Youssoufia', rating: 4.8, phone: '06 69 83 44 17', lat: 33.9928, lng: -6.8413 },
  { id: 290, name: 'TOUIL Mohamed', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.7, phone: '06 61 54 17 93', lat: 34.037, lng: -6.831 },
  { id: 291, name: 'EL MISK Abdelkader', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.6, phone: '06 63 10 85 77', lat: 34.0621, lng: -6.8741 },
  { id: 292, name: 'EL MHAIDI Mahjoub', serviceId: 'electrical', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.9, phone: '06 63 12 86 59', lat: 34.0031, lng: -6.8211 },

  // Marrakech Electricians
  { id: 293, name: 'Naqouri Abdelmourhit', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'LOUMA 4 NO 1 HAY CHATOUI', rating: 4.8, phone: '0670216923', lat: 31.6373, lng: -8.024 },
  { id: 294, name: 'elfajri younes', serviceId: 'electrical', serviceCities: ['Marrakech'], address: '', rating: 4.6, phone: '0648998330', lat: 31.6212, lng: -8.0264 },
  { id: 295, name: 'AAbdou Electricien', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Geuliz', rating: 4.9, phone: '0648227725', lat: 31.5866, lng: -7.957 },
  { id: 296, name: 'Mehri Mansour', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'NO 175 DB MEHRI DR AKIOUD', rating: 4.7, phone: '0677701509', lat: 31.6384, lng: -7.9405 },
  { id: 297, name: 'Hamza Elhamza', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Daoudyate wahda 5', rating: 4.5, phone: '0678302863', lat: 31.6256, lng: -7.9868 },
  { id: 298, name: 'Mohamed Ali', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Marrakech', rating: 4.8, phone: '0675009697', lat: 31.6441, lng: -7.9421 },
  { id: 299, name: 'abde lfattah bouskne', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'AL MASSIRA', rating: 4.6, phone: '0666631223', lat: 31.6496, lng: -7.9416 },
  { id: 300, name: 'Lahcen Lahcen', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Marrakech', rating: 4.9, phone: '0661977936', lat: 31.6702, lng: -8.012 },
  { id: 301, name: 'abd slam kodsi', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'lot les palmiers 1 nr 552 targa', rating: 4.7, phone: '0654507554 // 0634678590', lat: 31.6293, lng: -7.9625 },
  { id: 302, name: 'omari abdeljalil', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'N 41 unité 2 daoudiate', rating: 4.8, phone: '0642596568', lat: 31.6033, lng: -8.0061 },
  { id: 303, name: 'rifaai hassan', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'L harakat n 23 tasltant', rating: 4.5, phone: '0676842151', lat: 31.6448, lng: -8.0195 },
  { id: 304, name: 'Oberka Redouane', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Socoma askejour n° 513', rating: 4.7, phone: '0674026264', lat: 31.666, lng: -7.9511 },
  { id: 305, name: 'omari abdeljalil', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'N 41 unite 2 daoudiat', rating: 4.9, phone: '0674156498', lat: 31.6416, lng: -7.9942 },
  { id: 306, name: 'R.E.S.T.D Travaux divers', serviceId: 'electrical', serviceCities: ['Marrakech'], address: '72 lot zaitouna rue al inab, mhamid', rating: 4.6, phone: '0660558377', lat: 31.6579, lng: -7.9388 },
  { id: 307, name: 'Ste zayd tech Liyazid', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Massira', rating: 4.8, phone: '0675712224', lat: 31.6214, lng: -8.0163 },
  { id: 308, name: 'AIT BEN SALEH Abdellatif', serviceId: 'electrical', serviceCities: ['Marrakech'], address: '', rating: 4.5, phone: '0673629584', lat: 31.6738, lng: -7.9377 },
  { id: 309, name: 'AZNAG Anass', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'M\'hamid', rating: 4.7, phone: '06 70 68 74 05', lat: 31.6617, lng: -7.9701 },
  { id: 310, name: 'Jomar Abdessamad', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Marrakech', rating: 4.9, phone: '0673564812', lat: 31.5975, lng: -8.0055 },
  { id: 311, name: 'Bricolage a domicile abdessamad abdel', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Marrakech', rating: 4.6, phone: '00212663662865', lat: 31.6678, lng: -7.9408 },
  { id: 312, name: 'CADI Youssef', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'DAOUDIAT , SAADA ,IZDIHAR', rating: 4.8, phone: '0675782109', lat: 31.6288, lng: -7.9997 },
  { id: 313, name: 'EL KAKKAT Abdelkabir', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.7, phone: '06 67 84 94 28', lat: 31.6441, lng: -8.0298 },
  { id: 314, name: 'AL KOYAD Ibrahim', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.6, phone: '06 64 84 92 73', lat: 31.5833, lng: -7.9944 },
  { id: 315, name: 'LIKAYNI Mehdi', serviceId: 'electrical', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.9, phone: '06 61 72 78 79', lat: 31.582, lng: -8.0287 }
];

export const PROFESSIONALS = professionalsData;

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    main_heading: 'Professional Home Services On Demand',
    sub_heading: 'Connect with trusted plumbers, electricians, and painters in Morocco.',
    search_placeholder: 'What service do you need?',
    search_button: 'Search',
    our_services: 'Our Services',
    find_a_pro: 'Find a Professional',
    results_found_one: '1 professional found',
    results_found_other: '{count} professionals found',
    no_pros_found: 'No professionals found matching your criteria.',
    view_profile: 'View Profile',
    filter_by_city: 'Filter by city',
    all_cities: 'All Cities',
    map_title: 'Find Professionals Near You',
    map_select_category_prompt: 'Select a category above to see professionals on the map',
    finding_location: 'Locating...',
    find_near_me: 'Find Near Me',
    nearby_professionals: 'Nearby Professionals',
    distance_km: '{dist} km away',
    login_signup: 'Login / Sign Up',
    post_a_job: 'Post a Job',
    job_board: 'Job Board',
    my_activity: 'My Activity',
    support: 'Support',
    footer_company: 'Company',
    footer_contact: 'Contact Us',
    footer_privacy_policy: 'Privacy Policy',
    footer_usage_guidelines: 'Usage Guidelines',
    all_rights_reserved: 'All rights reserved.',
    previous: 'Previous',
    next: 'Next',
    cant_find_pro: "Can't find the right professional?",
    post_a_job_cta: "Post a Job Request",
    post_job_subtext: "Tell us what you need and receive offers from qualified pros.",
    // Auth & Profile
    welcome_back: 'Welcome Back',
    create_account: 'Create Your Account',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    logout: 'Logout',
    email_address: 'Email Address',
    password: 'Password',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    role_client: 'Client (Looking for a service)',
    role_provider: 'Provider (Offering a service)',
    // Pricing
    pricing_title: 'Simple, Transparent Pricing',
    pricing_subtitle_1: 'Choose the plan that fits your business needs.',
    pricing_subtitle_2: 'Start growing your client base today.',
    plan_standard_name: 'Standard Plan',
    plan_standard_desc: 'Perfect for getting started.',
    plan_standard_feature_1: 'Create a professional profile',
    plan_standard_feature_2: 'List your services in one city',
    plan_standard_feature_3: 'Receive up to 5 job leads/month',
    plan_standard_feature_4: 'Basic support',
    plan_standard_cta: 'Get Started',
    plan_premium_name: 'Premium Plan',
    plan_premium_desc: 'Best for established professionals.',
    plan_premium_feature_1: 'Everything in Standard',
    plan_premium_feature_2: 'List in multiple cities',
    plan_premium_feature_3: 'Unlimited job leads',
    plan_premium_feature_4: 'Priority listing in search',
    plan_premium_feature_5: 'Priority support',
    plan_premium_cta: 'Go Premium',
    price_unit: 'MAD/month',
    plan_featured_badge: 'Most Popular',
    // Payment
    payment_title: 'Upgrade to Premium',
    payment_subtitle: 'Complete your payment to activate your account.',
    payment_holder_name_label: 'Account Holder Name',
    payment_holder_name_value: 'Brikole SARL',
    payment_rib_label: 'RIB (Bank Account Number)',
    payment_reference_label: 'Payment Reference',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'Please make a transfer to the bank account above. Your account will be activated within 24 hours of receipt.',
    payment_done_button: 'I have made the transfer',
    // Job Post
    create_job_request: 'Create Job Request',
    job_title: 'Job Title',
    job_description: 'Description',
    category: 'Category',
    city: 'City',
    budget: 'Budget (MAD)',
    budget_type: 'Budget Type',
    fixed_price: 'Fixed Price',
    negotiable: 'Negotiable',
    submit_job_post: 'Post Job',
    job_posted_successfully: 'Job posted successfully!',
    // Job Board
    open_jobs_near_you: 'Open jobs near you.',
    no_open_jobs: 'No open jobs found.',
    view_details_and_apply: 'View Details & Apply',
    make_an_offer: 'Make an Offer',
    your_offer: 'Your Offer (MAD)',
    optional_message: 'Message (Optional)',
    submit_offer: 'Submit Offer',
    offer_submitted: 'Offer submitted successfully!',
    // My Activity
    my_jobs: 'My Jobs',
    my_offers: 'My Offers',
    view_offers: 'View Offers',
    offers_received: 'Offers Received',
    job_awarded: 'Job Awarded',
    contact_provider_at: 'Contact provider at: {phone}',
    no_offers_yet: 'No offers yet.',
    accept_offer: 'Accept Offer',
    offer_accepted: 'Offer Accepted',
    offer_rejected: 'Offer Rejected',
    offer_pending: 'Pending',
    // Contact & Support
    contact_us_title: 'Contact Us',
    contact_us_subtitle: 'We are here to help. Send us a message.',
    your_name: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    send_message: 'Send Message',
    message_sent_success: 'Message sent successfully!',
    my_tickets: 'My Support Tickets',
    create_new_ticket: 'Create New Ticket',
    no_tickets_found: 'No support tickets found.',
    back_to_tickets: 'Back to Tickets',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    submit_ticket: 'Submit Ticket',
    replies: 'Replies',
    add_reply: 'Add a reply...',
    no_new_messages: 'No new messages.',
    no_archived_messages: 'No archived messages.',
    show_new: 'Show New',
    show_archived: 'Show Archived',
    archive: 'Archive',
    // Static Pages
    privacy_policy_title: 'Privacy Policy',
    last_updated: 'Last Updated:',
    privacy_h2_intro: '1. Introduction',
    privacy_p_intro: 'Welcome to Brikole. We respect your privacy and are committed to protecting your personal data.',
    privacy_h2_info_collect: '2. Information We Collect',
    privacy_p_info_collect: 'We may collect various types of information, including:',
    privacy_li_personal_data_title: 'Personal Data:',
    privacy_li_personal_data_desc: 'Name, email, phone number, etc.',
    privacy_li_usage_data_title: 'Usage Data:',
    privacy_li_usage_data_desc: 'How you interact with our service.',
    privacy_li_geolocation_title: 'Geolocation:',
    privacy_li_geolocation_desc: 'To find nearby professionals.',
    privacy_h2_how_we_use: '3. How We Use Your Information',
    privacy_p_how_we_use: 'We use your data to:',
    privacy_li_use_1: 'Provide and maintain our Service',
    privacy_li_use_2: 'Notify you about changes',
    privacy_li_use_3: 'Allow interactive features',
    privacy_li_use_4: 'Provide customer support',
    privacy_li_use_5: 'Gather analysis to improve',
    privacy_li_use_6: 'Monitor usage',
    privacy_li_use_7: 'Detect and prevent technical issues',
    privacy_h2_disclosure: '4. Disclosure of Data',
    privacy_p_disclosure: 'We may disclose your personal data in good faith belief that such action is necessary to:',
    privacy_li_disclosure_1_title: 'Legal Obligation:',
    privacy_li_disclosure_1_desc: 'To comply with a legal obligation.',
    privacy_li_disclosure_2_title: 'Protection:',
    privacy_li_disclosure_2_desc: 'To protect and defend the rights or property of Brikole.',
    privacy_h2_security: '5. Security of Data',
    privacy_p_security: 'The security of your data is important to us, but remember that no method of transmission over the Internet is 100% secure.',
    privacy_h2_changes: '6. Changes to This Policy',
    privacy_p_changes: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
    privacy_h2_contact: '7. Contact Us',
    privacy_p_contact: 'If you have any questions about this Privacy Policy, please contact us.',
    
    guidelines_title: 'Usage Guidelines',
    effective_date: 'Effective Date:',
    guidelines_h2_intro: 'Introduction',
    guidelines_p_intro: 'These guidelines are designed to ensure a safe and positive experience for all users of Brikole.',
    guidelines_h2_for_clients: 'For Clients',
    guidelines_li_client_1_title: 'Accurate Information:',
    guidelines_li_client_1_desc: 'Provide clear and accurate details about the job.',
    guidelines_li_client_2_title: 'Respect:',
    guidelines_li_client_2_desc: 'Treat service providers with respect and courtesy.',
    guidelines_li_client_3_title: 'Safety:',
    guidelines_li_client_3_desc: 'Ensure a safe working environment for the provider.',
    guidelines_li_client_4_title: 'Payment:',
    guidelines_li_client_4_desc: 'Agree on payment terms clearly before work begins.',
    guidelines_h2_for_providers: 'For Service Providers',
    guidelines_li_provider_1_title: 'Professionalism:',
    guidelines_li_provider_1_desc: 'Maintain high standards of workmanship and conduct.',
    guidelines_li_provider_2_title: 'Punctuality:',
    guidelines_li_provider_2_desc: 'Arrive on time for appointments.',
    guidelines_li_provider_3_title: 'Transparency:',
    guidelines_li_provider_3_desc: 'Be transparent about pricing and services.',
    guidelines_li_provider_4_title: 'Compliance:',
    guidelines_li_provider_4_desc: 'Comply with all local laws and regulations.',
    guidelines_li_provider_5_title: 'Quality:',
    guidelines_li_provider_5_desc: 'Ensure the quality of materials and work.',
    guidelines_h2_prohibited: 'Prohibited Activities',
    guidelines_p_prohibited: 'The following activities are strictly prohibited:',
    guidelines_li_prohibited_1: 'Fraudulent or misleading behavior.',
    guidelines_li_prohibited_2: 'Harassment or hate speech.',
    guidelines_li_prohibited_3: 'Posting illegal or dangerous content.',
    guidelines_li_prohibited_4: 'Spamming or soliciting unrelated services.',
    guidelines_li_prohibited_5: 'Creating fake accounts or reviews.',
    guidelines_h2_enforcement: 'Enforcement',
    guidelines_p_enforcement: 'Violations of these guidelines may result in account suspension or termination.',
  },
  fr: {
    main_heading: 'Services à Domicile Professionnels à la Demande',
    sub_heading: 'Connectez-vous avec des plombiers, électriciens et peintres de confiance au Maroc.',
    search_placeholder: 'De quel service avez-vous besoin ?',
    search_button: 'Rechercher',
    our_services: 'Nos Services',
    find_a_pro: 'Trouver un Professionnel',
    results_found_one: '1 professionnel trouvé',
    results_found_other: '{count} professionnels trouvés',
    no_pros_found: 'Aucun professionnel trouvé correspondant à vos critères.',
    view_profile: 'Voir le Profil',
    filter_by_city: 'Filtrer par ville',
    all_cities: 'Toutes les villes',
    map_title: 'Trouver des Professionnels près de chez vous',
    map_select_category_prompt: 'Sélectionnez une catégorie ci-dessus pour voir les professionnels sur la carte',
    finding_location: 'Localisation...',
    find_near_me: 'Trouver près de moi',
    nearby_professionals: 'Professionnels à proximité',
    distance_km: 'À {dist} km',
    login_signup: 'Connexion / Inscription',
    post_a_job: 'Publier une annonce',
    job_board: 'Offres d\'emploi',
    my_activity: 'Mon Activité',
    support: 'Support',
    footer_company: 'Entreprise',
    footer_contact: 'Contactez-nous',
    footer_privacy_policy: 'Politique de Confidentialité',
    footer_usage_guidelines: 'Conditions d\'utilisation',
    all_rights_reserved: 'Tous droits réservés.',
    previous: 'Précédent',
    next: 'Suivant',
    cant_find_pro: "Vous ne trouvez pas le bon professionnel ?",
    post_a_job_cta: "Publier une demande",
    post_job_subtext: "Dites-nous ce dont vous avez besoin et recevez des offres.",
    // Auth & Profile
    welcome_back: 'Bon retour',
    create_account: 'Créer votre compte',
    sign_in: 'Se connecter',
    sign_up: 'S\'inscrire',
    logout: 'Déconnexion',
    email_address: 'Adresse Email',
    password: 'Mot de passe',
    full_name: 'Nom Complet',
    phone_number: 'Numéro de Téléphone',
    role_client: 'Client (Je cherche un service)',
    role_provider: 'Prestataire (Je propose un service)',
     // Pricing
    pricing_title: 'Tarification Simple et Transparente',
    pricing_subtitle_1: 'Choisissez le plan adapté à vos besoins.',
    pricing_subtitle_2: 'Commencez à développer votre clientèle aujourd\'hui.',
    plan_standard_name: 'Plan Standard',
    plan_standard_desc: 'Parfait pour débuter.',
    plan_standard_feature_1: 'Créer un profil professionnel',
    plan_standard_feature_2: 'Lister vos services dans une ville',
    plan_standard_feature_3: 'Recevoir jusqu\'à 5 offres/mois',
    plan_standard_feature_4: 'Support basique',
    plan_standard_cta: 'Commencer',
    plan_premium_name: 'Plan Premium',
    plan_premium_desc: 'Idéal pour les professionnels établis.',
    plan_premium_feature_1: 'Tout dans le plan Standard',
    plan_premium_feature_2: 'Lister dans plusieurs villes',
    plan_premium_feature_3: 'Offres illimitées',
    plan_premium_feature_4: 'Priorité dans les recherches',
    plan_premium_feature_5: 'Support prioritaire',
    plan_premium_cta: 'Passer Premium',
    price_unit: 'MAD/mois',
    plan_featured_badge: 'Le Plus Populaire',
    // Payment
    payment_title: 'Passer à Premium',
    payment_subtitle: 'Effectuez votre paiement pour activer votre compte.',
    payment_holder_name_label: 'Nom du Titulaire du Compte',
    payment_holder_name_value: 'Brikole SARL',
    payment_rib_label: 'RIB (Numéro de Compte Bancaire)',
    payment_reference_label: 'Référence de Paiement',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'Veuillez effectuer un virement sur le compte bancaire ci-dessus. Votre compte sera activé dans les 24 heures suivant la réception.',
    payment_done_button: 'J\'ai effectué le virement',
    // Job Post
    create_job_request: 'Créer une demande',
    job_title: 'Titre de la demande',
    job_description: 'Description',
    category: 'Catégorie',
    city: 'Ville',
    budget: 'Budget (MAD)',
    budget_type: 'Type de Budget',
    fixed_price: 'Prix Fixe',
    negotiable: 'Négociable',
    submit_job_post: 'Publier la demande',
    job_posted_successfully: 'Demande publiée avec succès !',
    // Job Board
    open_jobs_near_you: 'Offres disponibles près de chez vous.',
    no_open_jobs: 'Aucune offre disponible.',
    view_details_and_apply: 'Voir Détails & Postuler',
    make_an_offer: 'Faire une offre',
    your_offer: 'Votre Offre (MAD)',
    optional_message: 'Message (Optionnel)',
    submit_offer: 'Soumettre l\'offre',
    offer_submitted: 'Offre soumise avec succès !',
    // My Activity
    my_jobs: 'Mes Demandes',
    my_offers: 'Mes Offres',
    view_offers: 'Voir les Offres',
    offers_received: 'Offres Reçues',
    job_awarded: 'Attribué',
    contact_provider_at: 'Contacter le prestataire au : {phone}',
    no_offers_yet: 'Aucune offre pour le moment.',
    accept_offer: 'Accepter l\'offre',
    offer_accepted: 'Offre Acceptée',
    offer_rejected: 'Offre Rejetée',
    offer_pending: 'En Attente',
     // Contact & Support
    contact_us_title: 'Contactez-nous',
    contact_us_subtitle: 'Nous sommes là pour vous aider.',
    your_name: 'Votre Nom',
    subject: 'Sujet',
    message: 'Message',
    send_message: 'Envoyer le message',
    message_sent_success: 'Message envoyé avec succès !',
    my_tickets: 'Mes Tickets Support',
    create_new_ticket: 'Créer un Nouveau Ticket',
    no_tickets_found: 'Aucun ticket de support trouvé.',
    back_to_tickets: 'Retour aux Tickets',
    priority: 'Priorité',
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    submit_ticket: 'Soumettre le Ticket',
    replies: 'Réponses',
    add_reply: 'Ajouter une réponse...',
    no_new_messages: 'Pas de nouveaux messages.',
    no_archived_messages: 'Pas de messages archivés.',
    show_new: 'Voir Nouveaux',
    show_archived: 'Voir Archivés',
    archive: 'Archiver',
    // Static Pages
    privacy_policy_title: 'Politique de Confidentialité',
    last_updated: 'Dernière mise à jour :',
    privacy_h2_intro: '1. Introduction',
    privacy_p_intro: 'Bienvenue sur Brikole. Nous respectons votre vie privée et nous engageons à protéger vos données personnelles.',
    privacy_h2_info_collect: '2. Informations que nous collectons',
    privacy_p_info_collect: 'Nous pouvons collecter différents types d\'informations, notamment :',
    privacy_li_personal_data_title: 'Données Personnelles :',
    privacy_li_personal_data_desc: 'Nom, email, numéro de téléphone, etc.',
    privacy_li_usage_data_title: 'Données d\'Utilisation :',
    privacy_li_usage_data_desc: 'Comment vous interagissez avec notre service.',
    privacy_li_geolocation_title: 'Géolocalisation :',
    privacy_li_geolocation_desc: 'Pour trouver des professionnels à proximité.',
    privacy_h2_how_we_use: '3. Comment nous utilisons vos informations',
    privacy_p_how_we_use: 'Nous utilisons vos données pour :',
    privacy_li_use_1: 'Fournir et maintenir notre Service',
    privacy_li_use_2: 'Vous informer des changements',
    privacy_li_use_3: 'Permettre des fonctionnalités interactives',
    privacy_li_use_4: 'Fournir un support client',
    privacy_li_use_5: 'Recueillir des analyses pour améliorer',
    privacy_li_use_6: 'Surveiller l\'utilisation',
    privacy_li_use_7: 'Détecter et prévenir les problèmes techniques',
    privacy_h2_disclosure: '4. Divulgation des données',
    privacy_p_disclosure: 'Nous pouvons divulguer vos données personnelles si nous croyons de bonne foi que cela est nécessaire pour :',
    privacy_li_disclosure_1_title: 'Obligation Légale :',
    privacy_li_disclosure_1_desc: 'Se conformer à une obligation légale.',
    privacy_li_disclosure_2_title: 'Protection :',
    privacy_li_disclosure_2_desc: 'Protéger et défendre les droits ou la propriété de Brikole.',
    privacy_h2_security: '5. Sécurité des données',
    privacy_p_security: 'La sécurité de vos données est importante pour nous, mais rappelez-vous qu\'aucune méthode de transmission sur Internet n\'est sécurisée à 100 %.',
    privacy_h2_changes: '6. Modifications de cette politique',
    privacy_p_changes: 'Nous pouvons mettre à jour notre politique de confidentialité de temps à autre. Nous vous informerons de tout changement en publiant la nouvelle politique sur cette page.',
    privacy_h2_contact: '7. Contactez-nous',
    privacy_p_contact: 'Si vous avez des questions concernant cette politique de confidentialité, veuillez nous contacter.',
    
    guidelines_title: 'Conditions d\'utilisation',
    effective_date: 'Date d\'entrée en vigueur :',
    guidelines_h2_intro: 'Introduction',
    guidelines_p_intro: 'Ces directives sont conçues pour garantir une expérience sûre et positive pour tous les utilisateurs de Brikole.',
    guidelines_h2_for_clients: 'Pour les Clients',
    guidelines_li_client_1_title: 'Informations Précises :',
    guidelines_li_client_1_desc: 'Fournissez des détails clairs et précis sur le travail.',
    guidelines_li_client_2_title: 'Respect :',
    guidelines_li_client_2_desc: 'Traitez les prestataires de services avec respect et courtoisie.',
    guidelines_li_client_3_title: 'Sécurité :',
    guidelines_li_client_3_desc: 'Assurez un environnement de travail sûr pour le prestataire.',
    guidelines_li_client_4_title: 'Paiement :',
    guidelines_li_client_4_desc: 'Convenez clairement des modalités de paiement avant le début des travaux.',
    guidelines_h2_for_providers: 'Pour les Prestataires',
    guidelines_li_provider_1_title: 'Professionnalisme :',
    guidelines_li_provider_1_desc: 'Maintenez des normes élevées de travail et de conduite.',
    guidelines_li_provider_2_title: 'Ponctualité :',
    guidelines_li_provider_2_desc: 'Arrivez à l\'heure aux rendez-vous.',
    guidelines_li_provider_3_title: 'Transparence :',
    guidelines_li_provider_3_desc: 'Soyez transparent sur les prix et les services.',
    guidelines_li_provider_4_title: 'Conformité :',
    guidelines_li_provider_4_desc: 'Respectez toutes les lois et réglementations locales.',
    guidelines_li_provider_5_title: 'Qualité :',
    guidelines_li_provider_5_desc: 'Assurez la qualité des matériaux et du travail.',
    guidelines_h2_prohibited: 'Activités Interdites',
    guidelines_p_prohibited: 'Les activités suivantes sont strictement interdites :',
    guidelines_li_prohibited_1: 'Comportement frauduleux ou trompeur.',
    guidelines_li_prohibited_2: 'Harcèlement ou discours haineux.',
    guidelines_li_prohibited_3: 'Publication de contenu illégal ou dangereux.',
    guidelines_li_prohibited_4: 'Spam ou sollicitation de services non liés.',
    guidelines_li_prohibited_5: 'Création de faux comptes ou avis.',
    guidelines_h2_enforcement: 'Application',
    guidelines_p_enforcement: 'La violation de ces directives peut entraîner la suspension ou la résiliation du compte.',
  },
  ar: {
    main_heading: 'خدمات منزلية احترافية عند الطلب',
    sub_heading: 'تواصل مع سباكين وكهربائيين وصباغين موثوقين في المغرب.',
    search_placeholder: 'ما هي الخدمة التي تحتاجها؟',
    search_button: 'بحث',
    our_services: 'خدماتنا',
    find_a_pro: 'اعثر على محترف',
    results_found_one: 'تم العثور على محترف واحد',
    results_found_other: 'تم العثور على {count} محترفين',
    no_pros_found: 'لم يتم العثور على محترفين مطابقين لمعاييرك.',
    view_profile: 'عرض الملف الشخصي',
    filter_by_city: 'تصفية حسب المدينة',
    all_cities: 'كل المدن',
    map_title: 'ابحث عن المحترفين بالقرب منك',
    map_select_category_prompt: 'اختر فئة أعلاه لرؤية المحترفين على الخريطة',
    finding_location: 'جاري تحديد الموقع...',
    find_near_me: 'ابحث بجواري',
    nearby_professionals: 'محترفون بالجوار',
    distance_km: 'على بعد {dist} كم',
    login_signup: 'تسجيل الدخول / الاشتراك',
    post_a_job: 'انشر وظيفة',
    job_board: 'لوحة الوظائف',
    my_activity: 'نشاطي',
    support: 'الدعم',
    footer_company: 'الشركة',
    footer_contact: 'اتصل بنا',
    footer_privacy_policy: 'سياسة الخصوصية',
    footer_usage_guidelines: 'إرشادات الاستخدام',
    all_rights_reserved: 'جميع الحقوق محفوظة.',
    previous: 'السابق',
    next: 'التالي',
    cant_find_pro: "لم تجد المحترف المناسب؟",
    post_a_job_cta: "انشر طلب عمل",
    post_job_subtext: "أخبرنا بما تحتاجه وتلقى عروضًا من محترفين مؤهلين.",
    // Auth & Profile
    welcome_back: 'مرحبًا بعودتك',
    create_account: 'أنشئ حسابك',
    sign_in: 'تسجيل الدخول',
    sign_up: 'اشتراك',
    logout: 'تسجيل الخروج',
    email_address: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    full_name: 'الاسم الكامل',
    phone_number: 'رقم الهاتف',
    role_client: 'عميل (أبحث عن خدمة)',
    role_provider: 'مقدم خدمة (أعرض خدمة)',
    // Pricing
    pricing_title: 'أسعار بسيطة وشفافة',
    pricing_subtitle_1: 'اختر الخطة التي تناسب احتياجات عملك.',
    pricing_subtitle_2: 'ابدأ في تنمية قاعدة عملائك اليوم.',
    plan_standard_name: 'الخطة القياسية',
    plan_standard_desc: 'مثالية للبدء.',
    plan_standard_feature_1: 'إنشاء ملف تعريف مهني',
    plan_standard_feature_2: 'إدراج خدماتك في مدينة واحدة',
    plan_standard_feature_3: 'تلقي ما يصل إلى 5 فرص عمل/شهر',
    plan_standard_feature_4: 'دعم أساسي',
    plan_standard_cta: 'ابدأ الآن',
    plan_premium_name: 'الخطة المميزة',
    plan_premium_desc: 'الأفضل للمحترفين الراسخين.',
    plan_premium_feature_1: 'كل شيء في الخطة القياسية',
    plan_premium_feature_2: 'الإدراج في مدن متعددة',
    plan_premium_feature_3: 'فرص عمل غير محدودة',
    plan_premium_feature_4: 'أولوية الظهور في البحث',
    plan_premium_feature_5: 'دعم ذو أولوية',
    plan_premium_cta: 'اشترك في المميزة',
    price_unit: 'درهم/شهر',
    plan_featured_badge: 'الأكثر شيوعًا',
    // Payment
    payment_title: 'الترقية إلى بريميوم',
    payment_subtitle: 'أكمل الدفع لتفعيل حسابك.',
    payment_holder_name_label: 'اسم صاحب الحساب',
    payment_holder_name_value: 'بريكول ش.م.م',
    payment_rib_label: 'رقم التعريف البنكي (RIB)',
    payment_reference_label: 'مرجع الدفع',
    payment_reference_value: 'SUB-PREMIUM-USERID',
    payment_confirmation_note: 'يرجى إجراء تحويل إلى الحساب المصرفي أعلاه. سيتم تفعيل حسابك في غضون 24 ساعة من الاستلام.',
    payment_done_button: 'لقد قمت بالتحويل',
    // Job Post
    create_job_request: 'إنشاء طلب عمل',
    job_title: 'عنوان الوظيفة',
    job_description: 'الوصف',
    category: 'الفئة',
    city: 'المدينة',
    budget: 'الميزانية (درهم)',
    budget_type: 'نوع الميزانية',
    fixed_price: 'سعر ثابت',
    negotiable: 'قابل للتفاوض',
    submit_job_post: 'نشر الوظيفة',
    job_posted_successfully: 'تم نشر الوظيفة بنجاح!',
    // Job Board
    open_jobs_near_you: 'وظائف مفتوحة بالقرب منك.',
    no_open_jobs: 'لا توجد وظائف مفتوحة.',
    view_details_and_apply: 'عرض التفاصيل والتقديم',
    make_an_offer: 'قدم عرضًا',
    your_offer: 'عرضك (درهم)',
    optional_message: 'رسالة (اختياري)',
    submit_offer: 'إرسال العرض',
    offer_submitted: 'تم إرسال العرض بنجاح!',
    // My Activity
    my_jobs: 'وظائفي',
    my_offers: 'عروضي',
    view_offers: 'عرض العروض',
    offers_received: 'العروض المستلمة',
    job_awarded: 'تم الترسية',
    contact_provider_at: 'اتصل بمقدم الخدمة على: {phone}',
    no_offers_yet: 'لا توجد عروض بعد.',
    accept_offer: 'قبول العرض',
    offer_accepted: 'تم قبول العرض',
    offer_rejected: 'تم رفض العرض',
    offer_pending: 'قيد الانتظار',
    // Contact & Support
    contact_us_title: 'اتصل بنا',
    contact_us_subtitle: 'نحن هنا للمساعدة. أرسل لنا رسالة.',
    your_name: 'اسمك',
    subject: 'الموضوع',
    message: 'الرسالة',
    send_message: 'إرسال الرسالة',
    message_sent_success: 'تم إرسال الرسالة بنجاح!',
    my_tickets: 'تذاكر الدعم الخاصة بي',
    create_new_ticket: 'إنشاء تذكرة جديدة',
    no_tickets_found: 'لم يتم العثور على تذاكر دعم.',
    back_to_tickets: 'العودة إلى التذاكر',
    priority: 'الأولوية',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    submit_ticket: 'إرسال التذكرة',
    replies: 'الردود',
    add_reply: 'أضف ردًا...',
    no_new_messages: 'لا توجد رسائل جديدة.',
    no_archived_messages: 'لا توجد رسائل مؤرشفة.',
    show_new: 'عرض الجديد',
    show_archived: 'عرض المؤرشف',
    archive: 'أرشفة',
    // Static Pages
    privacy_policy_title: 'سياسة الخصوصية',
    last_updated: 'آخر تحديث:',
    privacy_h2_intro: '1. مقدمة',
    privacy_p_intro: 'مرحبًا بكم في بريكول. نحن نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية.',
    privacy_h2_info_collect: '2. المعلومات التي نجمعها',
    privacy_p_info_collect: 'قد نجمع أنواعًا مختلفة من المعلومات، بما في ذلك:',
    privacy_li_personal_data_title: 'البيانات الشخصية:',
    privacy_li_personal_data_desc: 'الاسم، البريد الإلكتروني، رقم الهاتف، إلخ.',
    privacy_li_usage_data_title: 'بيانات الاستخدام:',
    privacy_li_usage_data_desc: 'كيفية تفاعلك مع خدمتنا.',
    privacy_li_geolocation_title: 'تحديد الموقع الجغرافي:',
    privacy_li_geolocation_desc: 'للعثور على محترفين بالقرب منك.',
    privacy_h2_how_we_use: '3. كيف نستخدم معلوماتك',
    privacy_p_how_we_use: 'نستخدم بياناتك لـ:',
    privacy_li_use_1: 'توفير وصيانة خدمتنا',
    privacy_li_use_2: 'إعلامك بالتغييرات',
    privacy_li_use_3: 'السماح بالميزات التفاعلية',
    privacy_li_use_4: 'تقديم الدعم للعملاء',
    privacy_li_use_5: 'جمع التحليلات للتحسين',
    privacy_li_use_6: 'مراقبة الاستخدام',
    privacy_li_use_7: 'كشف ومنع المشاكل التقنية',
    privacy_h2_disclosure: '4. الكشف عن البيانات',
    privacy_p_disclosure: 'قد نكشف عن بياناتك الشخصية بحسن نية إذا كان هذا الإجراء ضروريًا لـ:',
    privacy_li_disclosure_1_title: 'التزام قانوني:',
    privacy_li_disclosure_1_desc: 'للامتثال لالتزام قانوني.',
    privacy_li_disclosure_2_title: 'الحماية:',
    privacy_li_disclosure_2_desc: 'لحماية والدفاع عن حقوق أو ممتلكات بريكول.',
    privacy_h2_security: '5. أمن البيانات',
    privacy_p_security: 'أمن بياناتك مهم بالنسبة لنا، ولكن تذكر أنه لا توجد وسيلة نقل عبر الإنترنت آمنة بنسبة 100٪.',
    privacy_h2_changes: '6. تغييرات على هذه السياسة',
    privacy_p_changes: 'قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنقوم بإعلامك بأي تغييرات عن طريق نشر السياسة الجديدة على هذه الصفحة.',
    privacy_h2_contact: '7. اتصل بنا',
    privacy_p_contact: 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا.',

    guidelines_title: 'إرشادات الاستخدام',
    effective_date: 'تاريخ السريان:',
    guidelines_h2_intro: 'مقدمة',
    guidelines_p_intro: 'تم تصميم هذه الإرشادات لضمان تجربة آمنة وإيجابية لجميع مستخدمي بريكول.',
    guidelines_h2_for_clients: 'للعملاء',
    guidelines_li_client_1_title: 'معلومات دقيقة:',
    guidelines_li_client_1_desc: 'قدم تفاصيل واضحة ودقيقة حول الوظيفة.',
    guidelines_li_client_2_title: 'الاحترام:',
    guidelines_li_client_2_desc: 'عامل مقدمي الخدمات باحترام وكياسة.',
    guidelines_li_client_3_title: 'السلامة:',
    guidelines_li_client_3_desc: 'ضمان بيئة عمل آمنة لمقدم الخدمة.',
    guidelines_li_client_4_title: 'الدفع:',
    guidelines_li_client_4_desc: 'اتفق بوضوح على شروط الدفع قبل بدء العمل.',
    guidelines_h2_for_providers: 'لمقدمي الخدمات',
    guidelines_li_provider_1_title: 'الاحترافية:',
    guidelines_li_provider_1_desc: 'الحفاظ على معايير عالية من العمل والسلوك.',
    guidelines_li_provider_2_title: 'الالتزام بالمواعيد:',
    guidelines_li_provider_2_desc: 'الوصول في الوقت المحدد للمواعيد.',
    guidelines_li_provider_3_title: 'الشفافية:',
    guidelines_li_provider_3_desc: 'كن شفافًا بشأن الأسعار والخدمات.',
    guidelines_li_provider_4_title: 'الامتثال:',
    guidelines_li_provider_4_desc: 'الامتثال لجميع القوانين واللوائح المحلية.',
    guidelines_li_provider_5_title: 'الجودة:',
    guidelines_li_provider_5_desc: 'ضمان جودة المواد والعمل.',
    guidelines_h2_prohibited: 'الأنشطة المحظورة',
    guidelines_p_prohibited: 'يُحظر تمامًا الأنشطة التالية:',
    guidelines_li_prohibited_1: 'السلوك الاحتيالي أو المضلل.',
    guidelines_li_prohibited_2: 'التحرش أو خطاب الكراهية.',
    guidelines_li_prohibited_3: 'نشر محتوى غير قانوني أو خطير.',
    guidelines_li_prohibited_4: 'إرسال البريد العشوائي أو التماس خدمات غير ذات صلة.',
    guidelines_li_prohibited_5: 'إنشاء حسابات أو مراجعات وهمية.',
    guidelines_h2_enforcement: 'التنفيذ',
    guidelines_p_enforcement: 'قد تؤدي انتهاكات هذه الإرشادات إلى تعليق الحساب أو إنهائه.',
  },
};