import { ServiceCategory, Language, TranslationSet, Professional } from './types';
import { Wrench, PlugZap, PaintRoller, Droplets, Hammer, Sofa } from './components/icons';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'ar', name: 'العربية' },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    icon: Droplets,
    name: {
      en: 'Plumbing',
      fr: 'Plomberie',
      ar: 'السباكة',
    },
  },
  {
    id: 'electrical',
    icon: PlugZap,
    name: {
      en: 'Electrical',
      fr: 'Électricité',
      ar: 'الكهرباء',
    },
  },
  {
    id: 'painting',
    icon: PaintRoller,
    name: {
      en: 'Painting',
      fr: 'Peinture',
      ar: 'الدهان',
    },
  },
  {
    id: 'carpentry',
    icon: Hammer,
    name: {
      en: 'Carpentry',
      fr: 'Menuiserie',
      ar: 'النجارة',
    },
  },
   {
    id: 'general_repair',
    icon: Wrench,
    name: {
      en: 'General Repair',
      fr: 'Réparation Générale',
      ar: 'إصلاحات عامة',
    },
  },
  {
    id: 'assembly',
    icon: Sofa,
    name: {
      en: 'Furniture Assembly',
      fr: 'Montage de Meubles',
      ar: 'تركيب الأثاث',
    },
  },
];

export const PROFESSIONALS: Professional[] = [
  // Casablanca Plumbers
  { id: 1, name: 'ELWARDI Hassan', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Avenue Bordeaux', rating: 4.8, phone: '06 53 69 87 70' },
  { id: 2, name: 'EDDAIF Abdelmajid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.9, phone: '06 68 17 27 07' },
  { id: 3, name: 'FADLI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 42 75 38 93' },
  { id: 4, name: 'KOKAJI Simohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.6, phone: '06 65 83 19 61' },
  { id: 5, name: 'ELGARMA Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 75 47 64 51' },
  { id: 6, name: 'MOURAD Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.7, phone: '06 14 63 87 87' },
  { id: 7, name: 'AMROUG Hamid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '06 10 88 35 16' },
  { id: 8, name: 'ARGAZ Said', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Sebaa', rating: 4.8, phone: '06 00 57 29 47' },
  { id: 9, name: 'RAOUF Hicham', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.6, phone: '06 62 16 68 34' },
  { id: 10, name: 'ENNAKRI Abdelhadi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.7, phone: '06 15 74 15 33' },
  { id: 11, name: 'BEL KHADRASSI Abdelkarim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '06 67 26 85 15' },
  { id: 12, name: 'BEN ARBIA Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '06 66 30 30 44' },
  { id: 13, name: 'AL MISRA Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Moumen', rating: 4.8, phone: '06 71 46 18 99' },
  { id: 14, name: 'SENHAJI Abdennabi', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Ain Harrouda', rating: 4.7, phone: '06 62 01 74 59' },
  { id: 15, name: 'AIT BRAHIM Mohamed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 41 71 56 82' },
  { id: 16, name: 'ENNAINI Aziz', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.6, phone: '06 38 11 65 78' },
  { id: 17, name: 'ELASSOULI Houcine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.8, phone: '06 61 85 20 20' },
  { id: 18, name: 'KECHAF Rachid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.5, phone: '06 63 59 06 10' },
  { id: 19, name: 'ERAYHANI Khalid', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Verdin', rating: 4.7, phone: '06 64 74 33 46' },
  { id: 20, name: 'AHBARI Mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.9, phone: '06 60 95 89 83' },
  { id: 21, name: 'EL OUAFI Yassine', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.6, phone: '06 71 13 56 07' },
  { id: 22, name: 'ALAMI Karim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.8, phone: '06 69 87 45 21' },
  { id: 23, name: 'abdessamad biad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.5, phone: '0614149221' },
  { id: 24, name: 'HADDAD Ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '3, rue Ibrahim Hafid -ex Chateaubriand, Q. Gauthier - 20060', rating: 4.7, phone: '0522664088' },
  { id: 25, name: 'nachit ayoub', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'derb el wydad blok 511 n 748 hay hassani', rating: 4.9, phone: '0630113133' },
  { id: 26, name: 'Selmouni Brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Maarif', rating: 4.6, phone: '0670398387' },
  { id: 27, name: 'El Fissaoui Youness', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '61 rue 1 khalil 2 la villette', rating: 4.8, phone: '0678636249' },
  { id: 28, name: 'SOKTRA', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '9, Bd Abdelmoumen', rating: 4.5, phone: '0655904767' },
  { id: 29, name: 'Youness Boujmad', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Hay almasjid rue28 n 9 casa', rating: 4.7, phone: '0662713781' },
  { id: 30, name: 'mabsout abdelfattaj', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'Rue 12 imm 6 n 12 residence khaled sekelia hay hassani', rating: 4.9, phone: '0679648647' },
  { id: 31, name: 'maddah mohammed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'anassi al bernossi', rating: 4.6, phone: '0699901535' },
  { id: 32, name: 'Aitbelahsen ahmed', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: 'bloc saada 301 bd grande ceinture N 367', rating: 4.8, phone: '0660565036' },
  { id: 33, name: 'ibra brahim', serviceId: 'plumbing', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '0665426598' },
  
  // Rabat Plumbers
  { id: 34, name: 'ENNASRAOUI Jamal', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.7, phone: '06 41 14 66 24' },
  { id: 35, name: 'SMOUNI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 65 23 40 13/06 66 11 42 64' },
  { id: 36, name: 'SOUHADI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.6, phone: '06 22 68 47 03/06 77 92 19 67' },
  { id: 37, name: 'BENDADNI Bendadani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.5, phone: '05 37 69 91 93' },
  { id: 38, name: 'MBOUKI Omar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Takaddoum', rating: 4.9, phone: '06 73 30 49 49' },
  { id: 39, name: 'AADIM Youssef', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 74 37 23 73' },
  { id: 40, name: 'BOU INAN Abdelghani', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Yacoub Al Mansour', rating: 4.8, phone: '06 65 06 66 18 / 06 35 46 39 75' },
  { id: 41, name: 'AL MOHANDISS Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.6, phone: '06 70 94 05 83' },
  { id: 42, name: 'EL AMRANI Karim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 68 62 71 73' },
  { id: 43, name: 'BEROUMI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.5, phone: '06 22 62 03 58' },
  { id: 44, name: 'KERROUMI Mohamed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.7, phone: '06 66 08 12 52 / 06 6 1 32 10 42' },
  { id: 45, name: 'EL KALEM Ahmed', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.8, phone: '06 63 03 80 73' },
  { id: 46, name: 'DRISSAT Elarbi', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Hassan', rating: 4.6, phone: '06 68 01 22 03' },
  { id: 47, name: 'ERRAZITMI Abdelkabir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 78 34 79 62' },
  { id: 48, name: 'EL MAJDOULI Chankaoui', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'L\'Ocean', rating: 4.5, phone: '06 69 03 11 83' },
  { id: 49, name: 'MOUNDA Lehcen', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'El Akkari', rating: 4.7, phone: '06 66 32 53 06' },
  { id: 50, name: 'EL OUAZZANI Abdessamad', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.8, phone: '06 66 84 41 48' },
  { id: 51, name: 'ERRAMADI Said', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'Diour Jamaa', rating: 4.6, phone: '06 66 01 07 46' },
  { id: 52, name: 'EL ALAOUI Hassan', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '', rating: 4.9, phone: '06 63 88 81 20' },
  { id: 53, name: 'Ahmed Manar', serviceId: 'plumbing', serviceCities: ['Rabat'], address: '12 rue de hay riad', rating: 4.5, phone: '06636598541' },
  { id: 54, name: 'hicham chakir', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'agdal', rating: 4.7, phone: '0630892791' },
  { id: 55, name: 'samlali youness', serviceId: 'plumbing', serviceCities: ['Rabat', 'Témara'], address: 'masira 1 n 33', rating: 4.8, phone: '0617546262' },
  { id: 56, name: 'Naji Hicham', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N° 470 CYM', rating: 4.6, phone: '0623503918' },
  { id: 57, name: 'abdelmotalib ahdaf', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'AV HASSAN II N°24, Cité Almanar DIOUR JAMAA', rating: 4.9, phone: '06 23 47 77 12' },
  { id: 58, name: 'Boucetta Abderrahim', serviceId: 'plumbing', serviceCities: ['Rabat'], address: 'N 1343 hay el manzah cym', rating: 4.7, phone: '0661735121' },

  // Salé Plumbers
  { id: 59, name: 'EL GOUILI Lahcen', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 03 66 91' },
  { id: 60, name: 'IBRAHIMI Idrisse', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.8, phone: '06 60 36 77 14' },
  { id: 61, name: 'EL MAHDI Tabit', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 69 62 61 64' },
  { id: 62, name: 'OUAAZIZ Hassan', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Essalam', rating: 4.9, phone: '06 65 45 63 90' },
  { id: 63, name: 'CHERKAOUI Mohammed', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 66 31 44 95' },
  { id: 64, name: 'HDIDO Driss', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.7, phone: '0664 02 76 20' },
  { id: 65, name: 'LEMRABET Anas', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.8, phone: '06 65 19 90 76' },
  { id: 66, name: 'MOUNIR Rachid', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.6, phone: '06 13 68 72 23' },
  { id: 67, name: 'DAOUDI Aziz', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Rahma', rating: 4.9, phone: '06 65 46 94 39' },
  { id: 68, name: 'OUAAYAN Khalid', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Karima', rating: 4.5, phone: '06 62 73 29 48' },
  { id: 69, name: 'EL KLAYER Abdeljabar', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.7, phone: '06 67 68 10 02' },
  { id: 70, name: 'ZHAR Abdellah', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.8, phone: '06 61 76 54 76' },
  { id: 71, name: 'SAHRAOUI El Houssine', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Tabriquet', rating: 4.6, phone: '06 14 49 45 24' },
  { id: 72, name: 'EL GOUBI Mounir', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'Hay Chmaou', rating: 4.9, phone: '06 62 41 38 04 / 06 20 13 48 08' },
  { id: 73, name: 'AL MAHFOUDI Abdelghani', serviceId: 'plumbing', serviceCities: ['Salé'], address: '', rating: 4.5, phone: '06 70 32 56 10' },
  { id: 74, name: 'youssef maddahi', serviceId: 'plumbing', serviceCities: ['Salé'], address: 'N 45 rue essaouira sect nahda laayayda', rating: 4.7, phone: '0668277263' },

  // Marrakech Plumbers
  { id: 75, name: 'mohamed elbakouri', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate, Route Ourika', rating: 4.7, phone: '0660818600' },
  { id: 76, name: 'R.E.S.T.D Travaux divers', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '72 lot zaitouna rue al inab, Mhamid', rating: 4.8, phone: '0660558377' },
  { id: 77, name: 'tarik jawad', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'dwar iziki darb lhjam n 491', rating: 4.6, phone: '0662496544' },
  { id: 78, name: 'mohamed hada abid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '147 derb el massi syba', rating: 4.9, phone: '0676140995' },
  { id: 79, name: 'Ste zayd tech Liyazid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Massira', rating: 4.5, phone: '0675712224' },
  { id: 80, name: 'elfajri younes', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.7, phone: '0648998330' },
  { id: 81, name: 'Mohamed Ali', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.8, phone: '0675009697' },
  { id: 82, name: 'Abdslam Kodsi', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Massira, lot les palmies 1 n 552 targa', rating: 4.6, phone: '0654507554 // 0634678590' },
  { id: 83, name: 'rifaai hassan', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'L harakat n 23 tasltant', rating: 4.9, phone: '0676842151' },
  { id: 84, name: 'Mourad', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Les portes de Marrakech', rating: 4.7, phone: '0636144800' },
  { id: 85, name: 'EL GOUITI Abdelilah', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.8, phone: '06 63 51 92 35' },
  { id: 86, name: 'DOUKALI Radouane', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.6, phone: '06 70 25 22 42 / 06 00 26 26 41' },
  { id: 87, name: 'CHEMSEDDINE Kamal', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Mhamid', rating: 4.9, phone: '06 61 54 56 46' },
  { id: 88, name: 'MOHAMED Amine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'plombicom', rating: 4.5, phone: '06 99 56 91 21' },
  { id: 89, name: 'MUSTAPHA Mustapha', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Bab doukala arset al ahbasse N49 hay jazouli', rating: 4.7, phone: '06 98 20 85 15' },
  { id: 90, name: 'AIT BEN SALEH Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: '', rating: 4.8, phone: '0673629584' },
  { id: 91, name: 'ABUMANDIL Khalil', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 66 56 68 76' },
  { id: 92, name: 'JARDI Youness', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.5, phone: '06 68 77 44 36' },
  { id: 93, name: 'BEN CHAKROUNE Abderrahim', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.7, phone: '06 64 38 53 72' },
  { id: 94, name: 'CHALSI Mohammed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.8, phone: '06 71 36 38 20' },
  { id: 95, name: 'TIWAN Mounir', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Abwab Marrakech', rating: 4.6, phone: '06 15 26 50 77' },
  { id: 96, name: 'IWAHDA Rachid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.9, phone: '06 62 10 68 90' },
  { id: 97, name: 'ERROWAF Hamid', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.5, phone: '06 64 24 52 29' },
  { id: 98, name: 'AIT MBAREK Azeddine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Daoudiate', rating: 4.7, phone: '06 64 54 62 98' },
  { id: 99, name: 'DRAY Said', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.8, phone: '06 78 26 87 59' },
  { id: 100, name: 'IDRISSI Mohamed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.6, phone: '06 11 77 47 49' },
  { id: 101, name: 'SALAMTI Ibrahim', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 71 23 52 03' },
  { id: 102, name: 'AIT OUDRI Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Douar El Askar', rating: 4.5, phone: '06 61 72 48 45' },
  { id: 103, name: 'MOUTAWAKIL Abdellatif', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Youssoufia', rating: 4.7, phone: '06 71 57 80 34' },
  { id: 104, name: 'BOUTOBA Youssef', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.8, phone: '06 77 44 18 24' },
  { id: 105, name: 'OUALD ELHAMRIA Azeddine', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.6, phone: '06 10 51 30 12' },
  { id: 106, name: 'MAAROUF Ahmed', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Al Massira', rating: 4.9, phone: '06 72 64 11 99' },
  { id: 107, name: 'Himmich Said', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Gueliz', rating: 4.8, phone: '0610156881' },
  { id: 108, name: 'ayoub elmadimi', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'sidi youssef ben ali', rating: 4.6, phone: '0674994453' },
  { id: 109, name: 'EL YACOUBI MUSTAPHA', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'MHAMID 9', rating: 4.9, phone: '+212 698208515' },
  { id: 110, name: 'Abdelkrim Khlifa', serviceId: 'plumbing', serviceCities: ['Marrakech'], address: 'Madeira 1 -a-N665 3ème étage', rating: 4.7, phone: '0666238327' },
  
  // Tanger Plumbers
  { id: 111, name: 'Amrani Omar', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Marchane centre vile', rating: 4.8, phone: '0676628032' },
  { id: 112, name: 'yassin gerroug', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Boukhalf', rating: 4.6, phone: '0610105303' },
  { id: 113, name: 'BEN AMMAR Adnan', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Casabarata', rating: 4.9, phone: '06 63 16 95 63' },
  { id: 114, name: 'HAMDAN Abdessalam', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'Casabarata', rating: 4.7, phone: '06 61 75 84 90' },
  { id: 115, name: 'RBICHA Mohamed', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'boukhalef', rating: 4.5, phone: '0600705251' },
  { id: 116, name: 'BAKKALI Abdellatif', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'addoha albalia', rating: 4.8, phone: '0606642791' },
  { id: 117, name: 'Ahmed Joudi', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'jirari 2 rue 63 n 11', rating: 4.9, phone: '0626624408' },
  { id: 118, name: 'MOUSTAFA MOUSTAFA', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '0677534144' },
  { id: 119, name: 'anane abdi ila', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'drissia', rating: 4.8, phone: '0610852339' },
  { id: 120, name: 'Khalid Mazoun', serviceId: 'plumbing', serviceCities: ['Tanger'], address: 'R albait atique M 12 P 14 Masnana', rating: 4.7, phone: '0636518067' },

  // Agadir Region Plumbers
  { id: 121, name: 'Mestapha Dahraoui', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212601318316' },
  { id: 122, name: 'Youssef Chabi', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.8, phone: '+212610552729' },
  { id: 123, name: 'Zakaria Bila', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212630489659' },
  { id: 124, name: 'Youssef Bouhkoun', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+2120720452055' },
  { id: 125, name: 'Azdine Lkoute', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.5, phone: '+212667757744' },
  { id: 126, name: 'Aguersoul Hamid', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Taroudant', 'Tiznit'], address: '', rating: 4.7, phone: '+212655236011' },
  { id: 127, name: 'Abdelhakim Dahbi', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Ouarzazate', 'Taroudant', 'Tiznit'], address: '', rating: 4.8, phone: '+212677554188' },
  { id: 128, name: 'Mohamed Idali', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212781298217' },
  { id: 129, name: 'Adil Amghar', serviceId: 'plumbing', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+212667225133' },

  // Casablanca Electricians
  { id: 130, name: 'El Fissaoui Youness', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '61 rue 1 khalil 2 la villette', rating: 4.8, phone: '0678636249' },
  { id: 131, name: 'Edlouali Noureddine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '3 rue 27 derb korea', rating: 4.7, phone: '0707750342' },
  { id: 132, name: 'Chahbaoui Mhamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'AMAL 01 RUE 22 NR 06 ELBERNOUSSI', rating: 4.9, phone: '0664535754' },
  { id: 133, name: 'Arro Tarik', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Oulfa', rating: 4.6, phone: '+212689400857' },
  { id: 134, name: 'SOKTRA', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '9, Bd Abdelmoumen', rating: 4.8, phone: '0655904767' },
  { id: 135, name: 'Youness Boujmad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay almasjid rue28 n 9', rating: 4.5, phone: '0662713781' },
  { id: 136, name: 'demni aziz', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.7, phone: '0660893927' },
  { id: 137, name: 'Taloui Ahmed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Darbouazza', rating: 4.9, phone: '0661834481' },
  { id: 138, name: 'Mohamed Fathallah', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay oulfa', rating: 4.6, phone: '0615299351' },
  { id: 139, name: 'Selmouni Brahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Maarif', rating: 4.8, phone: '0670398387' },
  { id: 140, name: 'boubker jounaina', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'ain bourja', rating: 4.5, phone: '0613046494' },
  { id: 141, name: 'FARHAT Adio', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Hay bournazel', rating: 4.7, phone: '0620027992' },
  { id: 142, name: 'AMZOUZ Simohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Avenue Bordeaux', rating: 4.9, phone: '06 63 25 17 54' },
  { id: 143, name: 'EL MOAL Khalid', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.6, phone: '06 65 61 03 37' },
  { id: 144, name: 'EL HIMER Driss', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '06 61 81 23 96' },
  { id: 145, name: 'KHALFOUNE Abdessamiea', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.5, phone: '06 14 40 10 94' },
  { id: 146, name: 'ERRAMI Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.7, phone: '06 64 55 96 16' },
  { id: 147, name: 'SALMAN Driss', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '06 61 67 05 63' },
  { id: 148, name: 'EL BAHRAOUI Abderrahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Ain Sebaa', rating: 4.6, phone: '06 64 57 56 93' },
  { id: 149, name: 'ECHAHIR Abdelhak', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '06 65 13 12 84' },
  { id: 150, name: 'ETTINO Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.5, phone: '06 61 56 63 54' },
  { id: 151, name: 'Echchafi Mohamed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Res ALMANZAH GH21 RUE13 IMM6 N°5', rating: 4.7, phone: '+33661379672' },
  { id: 152, name: 'SOUFIAN soufian', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'hay moulay abdellah, rue 116 n 18,ain chock', rating: 4.9, phone: '0673168271' },
  { id: 153, name: 'FAIDAOUI Youssef', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Rue 1 n°56 Hay Essafa Oulfa', rating: 4.6, phone: '06 07 02 03 79' },
  { id: 154, name: 'abdessamad biad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Sidi Bernoussi', rating: 4.8, phone: '0614149221' },
  { id: 155, name: 'Lissiri Abdeltif', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bloc 46 n 51 bernnoussi 20600', rating: 4.5, phone: '0640436661' },
  { id: 156, name: 'nachit ayoub', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'derb el wydad blok 511 n 748 hay hassani', rating: 4.7, phone: '0630113133' },
  { id: 157, name: 'MOUSTAID Adil', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.9, phone: '06 63 22 71 22' },
  { id: 158, name: 'TAGHAZITE Abderrahman', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Anfa', rating: 4.6, phone: '06 61 59 44 13' },
  { id: 159, name: 'KASMI Hakim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Bourgogne', rating: 4.8, phone: '06 71 85 74 10' },
  { id: 160, name: 'FIKRI Mohammed', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.5, phone: '06 61 88 39 82' },
  { id: 161, name: 'FATHI Adil', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Belvédère', rating: 4.7, phone: '06 59 78 70 98 / 06 34 61 96 45' },
  { id: 162, name: 'ASSANI Jaber', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.9, phone: '06 61 61 74 79' },
  { id: 163, name: 'LAAOUBI Rachid', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.6, phone: '06 77 12 13 67' },
  { id: 164, name: 'EL BAGHDADI Mustapha', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Benjdia', rating: 4.8, phone: '06 79 16 68 53' },
  { id: 165, name: 'Abdlilah Elouardey', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Projet Hassan 2', rating: 4.8, phone: '0601590914' },
  { id: 166, name: 'sabar taoufik', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'ville errahma N 40 BC 14', rating: 4.6, phone: '0699341812' },
  { id: 167, name: 'Ferkani Amine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.9, phone: '0645758372' },
  { id: 168, name: 'CHAHID MEHDI', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '95 Rue 70 mabrouka', rating: 4.7, phone: '0661760902' },
  { id: 169, name: 'KAMAL MAGHNI', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Maarif, HAY WALAA IMM 24 NR 16 TR 18 SECT 02 SIDI MOUMEN', rating: 4.5, phone: '0667098476' },
  { id: 170, name: 'khabar abdelghani', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Oulfa', rating: 4.8, phone: '0667925505' },
  { id: 171, name: 'Amine Fikri', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'Rue 22 nr 107 sidi moumen', rating: 4.9, phone: '0762195162' },
  { id: 172, name: 'ibra brahim', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.6, phone: '0665426598' },
  { id: 173, name: 'Qariouh Omar', serviceId: 'electrical', serviceCities: ['Casablanca'], address: 'n 13 app c5 doha 2 jawhara', rating: 4.8, phone: '0652243656' },
  { id: 174, name: 'saidia ayad', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '', rating: 4.7, phone: '0661877150' },
  { id: 175, name: 'mohamed amine', serviceId: 'electrical', serviceCities: ['Casablanca'], address: '6 Rue Al Farabi', rating: 4.9, phone: '0665717495' },
  
  // Agadir Electricians
  { id: 176, name: 'Abderrahim Dekkousse', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212669587771' },
  { id: 177, name: 'Abderrahmane Bougzoul', serviceId: 'electrical', serviceCities: ['Agadir', 'Casablanca', 'Marrakech', 'Rabat', 'Meknès'], address: '', rating: 4.8, phone: '+212637636456' },
  { id: 178, name: 'Mohamed Lechgar', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane', 'Taroudant'], address: '', rating: 4.6, phone: '+212624048904' },
  { id: 179, name: 'Hassan Belamri', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.9, phone: '+212631856901' },
  { id: 180, name: 'Youssef Akrid', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.5, phone: '+212641856573' },
  { id: 181, name: 'Ibrahim Sghiri', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.7, phone: '+212665388279' },
  { id: 182, name: 'Faycal Lhathouti', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Inezgane'], address: '', rating: 4.8, phone: '+212716565030' },
  { id: 183, name: 'EL BOUZKIRI El Houssine', serviceId: 'electrical', serviceCities: ['Agadir'], address: '', rating: 4.6, phone: '06 51 66 10 89' },
  { id: 184, name: 'Mohamed Idali', serviceId: 'electrical', serviceCities: ['Agadir', 'Ait Melloul', 'Dcheira el Jihadia', 'Guelmim', 'Inezgane', 'Sidi Ifni', 'Tantan', 'Taroudant', 'Tiznit'], address: '', rating: 4.6, phone: '+212781298217' },

  // Tanger Region Electricians
  { id: 185, name: 'abdeljalil fraj', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Mobilité nationale', rating: 4.7, phone: '+212613255547' },
  { id: 186, name: 'Mohamed Rabie Afilal', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212660002973' },
  { id: 187, name: 'Said El Houali', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212604702766' },
  { id: 188, name: 'Mohamed Lfilali', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212605607597' },
  { id: 189, name: 'Mohamed Lfilali', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212605607597' },
  { id: 190, name: 'Hamza Lyaakoubi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212766868079' },
  { id: 191, name: 'Mohamed Benamti', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212681404339' },
  { id: 192, name: 'said Brico', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'ibiriya', rating: 4.8, phone: '0617675562' },
  { id: 193, name: 'SAIFI Hamza', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'place du 9 Avril', rating: 4.6, phone: '06 03 60 13 19' },
  { id: 194, name: 'AHROUCHE Kamal', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'aéroport tanger ibn batouta', rating: 4.9, phone: '0633976672' },
  { id: 195, name: 'ERBAHI Fouad', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'et les régions', rating: 4.7, phone: '0661770203' },
  { id: 196, name: 'anane abdi ila', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'drissia', rating: 4.6, phone: '0610852339' },
  { id: 197, name: 'boazza CHLAHBI', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'medina', rating: 4.9, phone: '0661001001' },
  { id: 198, name: 'Soufiane Hamouche', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Drissia', rating: 4.5, phone: '0630914113' },
  { id: 199, name: 'Alami Said', serviceId: 'electrical', serviceCities: ['Tanger'], address: 'Mojamma3 Al Hassani', rating: 4.7, phone: '0657052179' },
  { id: 200, name: 'Abderrahim Bakhti', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.8, phone: '+212630679336' },
  { id: 201, name: 'Mougha Mohamed', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212661656175' },
  { id: 202, name: 'Zoheir El Afia', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212649222036' },
  { id: 203, name: 'Adil Elmansouri', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.7, phone: '+212648032321' },
  { id: 204, name: 'Anas Elfhail', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212620179135' },
  { id: 205, name: 'Anas Elfhail', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.8, phone: '+212620179135' },
  { id: 206, name: 'Abdellah Adjou', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212703230359' },
  { id: 207, name: 'El Mattoute Yassine', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212703802921' },
  { id: 208, name: 'Hassan Nassiri', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212680343879' },
  { id: 209, name: 'Hassan Nassiri', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212680343879' },
  { id: 210, name: 'Oussama El ahmadi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212600013978' },
  { id: 211, name: 'Oussama El ahmadi', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212600013978' },
  { id: 212, name: 'Zbir Reda', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212606432807' },
  { id: 213, name: 'Jaouad Baazizi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212675619998' },
  { id: 214, name: 'Brahim Lachgar', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212604095719' },
  { id: 215, name: 'Ayoub Didi', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.7, phone: '+212623084540' },
  { id: 216, name: 'Ayoub Didi', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah', 'Fnideq', 'Ksar Sghir', 'M\'Diq', 'Martil', 'Tétouan'], address: '', rating: 4.7, phone: '+212623084540' },
  { id: 217, name: 'Mohsine Bekkari', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212624392615' },
  { id: 218, name: 'Abdelali Er Rosafy', serviceId: 'electrical', serviceCities: ['Tanger', 'Rabat', 'Salé', 'Aïn Aouda', 'Assilah', 'Kenitra', 'Tamesna', 'Témara'], address: '', rating: 4.6, phone: '+212658832494' },
  { id: 219, name: 'Abdelali Er Rosafy', serviceId: 'plumbing', serviceCities: ['Tanger', 'Rabat', 'Salé', 'Aïn Aouda', 'Assilah', 'Kenitra', 'Tamesna', 'Témara'], address: '', rating: 4.6, phone: '+212658832494' },
  { id: 220, name: 'Bilal Melouani', serviceId: 'electrical', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.9, phone: '+212605765742' },
  { id: 221, name: 'Bilal Melouani', serviceId: 'plumbing', serviceCities: ['Tanger', 'Assilah'], address: '', rating: 4.9, phone: '+212605765742' },
  { id: 222, name: 'Rachid Hamdane', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212620952285' },
  { id: 223, name: 'Mohamed Chrif Almousafir', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212651455785' },
  { id: 224, name: 'Mohamed Chrif Almousafir', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.7, phone: '+212651455785' },
  { id: 225, name: 'Otman Migou', serviceId: 'electrical', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212655988894' },
  { id: 226, name: 'Otman Migou', serviceId: 'plumbing', serviceCities: ['Tanger', 'Tétouan'], address: '', rating: 4.8, phone: '+212655988894' },
  { id: 227, name: 'Hamza Toudi', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.6, phone: '+212605304755' },
  { id: 228, name: 'Bilal Soufiani', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212631599411' },
  { id: 229, name: 'Bilal Soufiani', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.9, phone: '+212631599411' },
  { id: 230, name: 'Ayoub Aaryouch', serviceId: 'electrical', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212665683987' },
  { id: 231, name: 'Ayoub Aaryouch', serviceId: 'plumbing', serviceCities: ['Tanger'], address: '', rating: 4.5, phone: '+212665683987' },
];

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    main_heading: 'Find reliable help, instantly.',
    sub_heading: 'Your trusted partner for all home services in Morocco. Fast, professional, and at your service.',
    search_placeholder: 'What service do you need?',
    search_button: 'Search',
    our_services: 'Our Services',
    login_signup: 'Login / Sign Up',
    footer_about: 'About Us',
    footer_contact: 'Contact',
    footer_terms: 'Terms of Service',
    footer_privacy: 'Privacy Policy',
    all_rights_reserved: 'All rights reserved.',
    find_a_pro: 'Meet Our Top Professionals',
    view_profile: 'View Profile',
    no_pros_found: 'No professionals found for this category yet.',
    filter_by_city: 'Filter by City',
    all_cities: 'All Cities',
    results_found_one: 'Showing 1 result',
    results_found_other: 'Showing {count} results',
    previous: 'Previous',
    next: 'Next',
  },
  fr: {
    main_heading: 'Trouvez une aide fiable, instantanément.',
    sub_heading: 'Votre partenaire de confiance pour tous les services à domicile au Maroc. Rapide, professionnel et à votre service.',
    search_placeholder: 'De quel service avez-vous besoin ?',
    search_button: 'Rechercher',
    our_services: 'Nos Services',
    login_signup: 'Connexion / Inscription',
    footer_about: 'À propos de nous',
    footer_contact: 'Contact',
    footer_terms: 'Conditions d\'utilisation',
    footer_privacy: 'Politique de confidentialité',
    all_rights_reserved: 'Tous droits réservés.',
    find_a_pro: 'Découvrez Nos Meilleurs Professionnels',
    view_profile: 'Voir le Profil',
    no_pros_found: 'Aucun professionnel trouvé pour cette catégorie pour le moment.',
    filter_by_city: 'Filtrer par Ville',
    all_cities: 'Toutes les Villes',
    results_found_one: 'Affichage de 1 résultat',
    results_found_other: 'Affichage de {count} résultats',
    previous: 'Précédent',
    next: 'Suivant',
  },
  ar: {
    main_heading: 'اعثر على مساعدة موثوقة، على الفور.',
    sub_heading: 'شريكك الموثوق لجميع الخدمات المنزلية في المغرب. سريع، محترف، وفي خدمتك.',
    search_placeholder: 'ما هي الخدمة التي تحتاجها؟',
    search_button: 'بحث',
    our_services: 'خدماتنا',
    login_signup: 'تسجيل الدخول / اشتراك',
    footer_about: 'من نحن',
    footer_contact: 'اتصل بنا',
    footer_terms: 'شروط الخدمة',
    footer_privacy: 'سياسة الخصوصية',
    all_rights_reserved: 'كل الحقوق محفوظة.',
    find_a_pro: 'تعرف على أفضل المتخصصين لدينا',
    view_profile: 'عرض الملف الشخصي',
    no_pros_found: 'لم يتم العثور على متخصصين لهذه الفئة بعد.',
    filter_by_city: 'تصفية حسب المدينة',
    all_cities: 'كل المدن',
    results_found_one: 'إظهار نتيجة واحدة',
    results_found_other: 'إظهار {count} من النتائج',
    previous: 'السابق',
    next: 'التالي',
  },
};